### PR TITLE
s3_auth: Clear handling TSAction in the config_reloader

### LINKED ISSUE #10555: s3_auth: crash on S3Config destructor
We faced a crash of s3_auth plugin with our 9.2.x deployment.
```
[ 00 ] libpthread-2.17.so  __libc_waitpid                                                                                                                                                                     
[ 01 ] traffic_server      crash_logger_invoke                                                                                                                                                                ( Crash.cc:168 )
[ 02 ] libpthread-2.17.so                                                                                                                                                                                     
[ 03 ] <anonymous>                                                                                                                                                                                            
[ 04 ] s3_auth.so          TSRemapDeleteInstance                                                                                                                                                              ( s3_auth.cc:1221 )
[ 05 ] traffic_server                                                                                                                                                                                         ( RemapPluginInfo.cc:214 )
[ 06 ] traffic_server      done                                                                                                                                                                               ( PluginFactory.cc:66 )
[ 07 ] traffic_server      operator()                                                                                                                                                                         ( PluginFactory.cc:281 )
[ 08 ] traffic_server      operator()                                                                                                                                                                         ( IntrusiveDList.h:865 )
[ 09 ] traffic_server      Intrusive_DList_Apply<ts::IntrusiveLinkage<RemapPluginInst, &RemapPluginInst::_next, &RemapPluginInst::_prev>, (lambda at ../../../include/tscpp/util/IntrusiveDList.h:865:23) &>  ( IntrusiveDList.h:876 )
[ 10 ] traffic_server      apply<(lambda at ../../../include/tscpp/util/IntrusiveDList.h:865:23)>                                                                                                             ( IntrusiveDList.h:887 )
[ 11 ] traffic_server      Intrusive_DList_Apply<ts::IntrusiveLinkage<RemapPluginInst, &RemapPluginInst::_next, &RemapPluginInst::_prev>, (lambda at PluginFactory.cc:281:19) &>                              ( IntrusiveDList.h:865 )
[ 12 ] traffic_server      apply<(lambda at PluginFactory.cc:281:19)>                                                                                                                                         ( IntrusiveDList.h:887 )
[ 13 ] traffic_server      PluginFactory::deactivate()                                                                                                                                                        ( PluginFactory.cc:281 )
[ 14 ] traffic_server      UrlRewrite::~UrlRewrite()                                                                                                                                                          ( UrlRewrite.cc:116 )
[ 15 ] traffic_server      UrlRewrite::~UrlRewrite()                                                                                                                                                          ( UrlRewrite.cc:104 )
[ 16 ] traffic_server      DeleterContinuation<UrlRewrite>::dieEvent(int, void*)                                                                                                                              ( iocore/eventsystem/P_Freer.h:42 )
[ 17 ] traffic_server      handleEvent                                                                                                                                                                        ( I_Continuation.h:235 )
[ 18 ] traffic_server      EThread::process_event(Event*, int)                                                                                                                                                ( UnixEThread.cc:153 )
[ 19 ] traffic_server      EThread::process_queue(Queue<Event, Event::Link_link>*, int*, int*)                                                                                                                ( UnixEThread.cc:188 )
[ 20 ] traffic_server      EThread::execute_regular()                                                                                                                                                         ( UnixEThread.cc:248 )
[ 21 ] traffic_server      EThread::execute()                                                                                                                                                                 ( UnixEThread.cc:353 )
[ 22 ] traffic_server      spawn_thread_internal                                                                                                                                                              ( Thread.cc:79 )
[ 23 ] libpthread-2.17.so  start_thread           
```

gdb

```
(gdb) bt
#0  0x00007f8100a1af20 in ?? ()
#1  0x00007f8160a22380 in S3Config::~S3Config() (this=0x7f42147cdac0) at s3_auth/s3_auth.cc:213
#2  0x00007f8160a24693 in TSRemapDeleteInstance (ih=0x7f8100a213e0) at s3_auth/s3_auth.cc:1221
#3  0x000055921143ff36 in doneInstance (this=0x7f8135101800, ih=0x7f42147cdac0) at RemapPluginInfo.cc:214
#4  done (this=0x7f4214df2f20) at PluginFactory.cc:66
...
(gdb) frame 1
#1  0x00007f8160a22380 in S3Config::~S3Config() (this=0x7f42147cdac0) at s3_auth/s3_auth.cc:213
213          TSActionCancel(_conf_rld_act);
```

When this crash happens, we saw below error logs.
```
traffic_server[15139]: [ET_TASK 2] ERROR: [s3_auth] requires both shared and AWS secret configuration
```

### PR DESCRIPTION
**Pull request by masaori335**
Fix #10555.

Prior to the change, when s3_auth plugin fall into the error with invalid config file, the handling `TSAction _conf_rld_act` is not cleared.

### CODE REVIEW

File: plugins/s3_auth/s3_auth.cc [hunk 1]
```diff
@@ -1053,19 +1053,18 @@ int
 config_reloader(TSCont cont, TSEvent event, void *edata)
 {
   Dbg(dbg_ctl, "reloading configs");
-  S3Config *s3          = static_cast<S3Config *>(TSContDataGet(cont));
+  S3Config *s3 = static_cast<S3Config *>(TSContDataGet(cont));
+  std::unique_lock lock(s3->reload_mutex);
```
Comment (masaori335) [inline plugins/s3_auth/s3_auth.cc:1057]: It looks like this function is calling many `S3Config` functions that modifies the `s3` object, so acquiring the `reload_mutex` in the beginning seems better.

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

File: plugins/s3_auth/s3_auth.cc (hunk 1 above)
Comment (ywkaras) [reply plugins/s3_auth/s3_auth.cc:1057]: This is a shared mutex.  It only protects the data changed by copy_changes_from().

File: plugins/s3_auth/s3_auth.cc [hunk 2]
```diff
@@ -1053,19 +1053,18 @@ int
...
+  s3->check_current_action(edata);
```
Comment (ywkaras) [inline plugins/s3_auth/s3_auth.cc:1058]: Why did you move this call to be first?

Comment (masaori335) [reply plugins/s3_auth/s3_auth.cc:1058]: This is the main change. Prior to this change, the handling action is not cleared if the config is invalid ( returning without clearing the `_conf_rld_action` in line 1061 )

File: plugins/s3_auth/s3_auth.cc (hunk 1 above)
Comment (masaori335) [reply plugins/s3_auth/s3_auth.cc:1057]: Oh! I thought this is regular mutex...it'll be not simple fix. I'll rollback this change and let races go for now.

Comment (masaori335) [reply plugins/s3_auth/s3_auth.cc]: For the race, @moonchen is writing up the issue and approaches.

**Review by ywkaras — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

This has a trivial merge conflict due to TSDebug vs Dbg, which I resolved.
