### PR TITLE
Delete H2 stream before destroy

### LINKED ISSUE #2207: H2 BAD_ACCESS at Mutex_lock under load
I saw this crash twice. I was running five h2load processes with 100 streams per each.

```
* thread #6, name = '[ET_NET 11]', stop reason = EXC_BAD_ACCESS (code=1, address=0x50)
    frame #0: 0x0000000100021162 traffic_server`Mutex_lock(location=0x0000000003a05928, ahandler=0x0000000000000000, m=0x0000000000000000, t=0x0000000002404000) at I_Lock.h:409
   406 	  ProxyMutex *m, EThread *t)
   407 	{
   408 	  ink_assert(t != 0);
-> 409 	  if (m->thread_holding != t) {
   410 	    ink_mutex_acquire(&m->the_mutex);
   411 	    m->thread_holding = t;
   412 	    ink_assert(m->thread_holding);
(lldb) bt
* thread #6, name = '[ET_NET 11]', stop reason = EXC_BAD_ACCESS (code=1, address=0x50)
  * frame #0: 0x0000000100021162 traffic_server`Mutex_lock(location=0x0000000003a05928, ahandler=0x0000000000000000, m=0x0000000000000000, t=0x0000000002404000) at I_Lock.h:409
    frame #1: 0x00000001000512ee traffic_server`MutexLock::MutexLock(this=0x0000000003a05940, location=0x0000000003a05928, ahandler=0x0000000000000000, am=0x000000000279f120, t=0x0000000002404000) at I_Lock.h:507
    frame #2: 0x000000010003f1e5 traffic_server`MutexLock::MutexLock(this=0x0000000003a05940, location=0x0000000003a05928, ahandler=0x0000000000000000, am=0x000000000279f120, t=0x0000000002404000) at I_Lock.h:506
    frame #3: 0x00000001001a502f traffic_server`Http2ConnectionState::send_a_data_frame(this=0x0000000000cf9e58, stream=0x000000000279f100, payload_length=0x0000000003a05a28) at Http2ConnectionState.cc:1258
    frame #4: 0x00000001001a326a traffic_server`Http2ConnectionState::send_data_frames_depends_on_priority(this=0x0000000000cf9e58) at Http2ConnectionState.cc:1219
    frame #5: 0x00000001001a1401 traffic_server`Http2ConnectionState::main_event_handler(this=0x0000000000cf9e58, event=2254, edata=0x0000000002828380) at Http2ConnectionState.cc:880
    frame #6: 0x000000010001e0f0 traffic_server`Continuation::handleEvent(this=0x0000000000cf9e58, event=2254, data=0x0000000002828380) at I_Continuation.h:153
    frame #7: 0x000000010033da95 traffic_server`EThread::process_event(this=0x0000000002404000, e=0x0000000002828380, calling_code=2254) at UnixEThread.cc:122
    frame #8: 0x000000010033e1c9 traffic_server`EThread::execute(this=0x0000000002404000) at UnixEThread.cc:234
    frame #9: 0x000000010033ce2c traffic_server`spawn_thread_internal(a=0x00000000009070f0) at Thread.cc:91
    frame #10: 0x000000000075093b libsystem_pthread.dylib`_pthread_body + 180
    frame #11: 0x0000000000750887 libsystem_pthread.dylib`_pthread_start + 286
    frame #12: 0x000000000075008d libsystem_pthread.dylib`thread_start + 13
```

```
(lldb) p *stream
(Http2Stream) $8 = {
(snip)
  header_blocks_length = 12
  request_header_length = 12
  recv_end_stream = true
  send_end_stream = false
  sent_request_header = false
  response_header_done = true
  request_sent = false
  is_first_transaction_flag = false
(snip)
  trailing_header = false
  body_done = false
  chunked = false
  closed = true
  reentrancy_count = 0
  terminate_stream = true
  data_length = 0
  bytes_sent = 41940160
(snip)
  cross_thread_event = 0x0000000000000000
  active_timeout = 300000000000
  active_event = 0x0000000000000000
  inactive_timeout = 30000000000
  inactive_timeout_at = 0
  inactive_event = 0x0000000000000000
  read_event = 0x0000000000000000
  write_event = 0x0000000000000000
}

```

### PR DESCRIPTION
**Pull request by maskit**
`delete_stream()` removes a stream from `priority_tree`, but here, the stream destroy itself without calling `delete_stream()`. The stream can be used during processing `HTTP2_SESSION_EVENT_XMIT`.

I think this fixes #2207.

### CODE REVIEW

File: proxy/http2/Http2Stream.cc [hunk 1]
```diff
@@ -124,6 +124,9 @@ Http2Stream::main_event_handler(int event, void *edata)
   reentrancy_count--;
   // Clean stream up if the terminate flag is set and we are at the bottom of the handler stack
   if (terminate_stream && reentrancy_count == 0) {
+    Http2ClientSession *h2_parent = static_cast<Http2ClientSession *>(parent);
+    SCOPED_MUTEX_LOCK(lock, h2_parent->connection_state.mutex, this_ethread());
+    h2_parent->connection_state.delete_stream(this);
```
Comment (masaori335) [inline proxy/http2/Http2Stream.cc]: These block looks similar to L667-L681 ( `Http2Stream::destroy()` ).
https://github.com/apache/trafficserver/blob/6dcc822baf23b1ab69c9a2609fc4f65fd9f6c10b/proxy/http2/Http2Stream.cc#L667-L681
How about calling `delete_stream()` before `release_stream()` in `Http2Stream::destroy()` ?

Comment (maskit) [reply proxy/http2/Http2Stream.cc]: I think the block in `destroy()` is a part of safety net. That may strengthen the safety net, however, I think `destroy` should do only destroying, and we shouldn't depend on the safety net.

Comment (shinrich) [reply proxy/http2/Http2Stream.cc]: Yes, I agree that the delete_stream/release_stream/destroy relationship isn't very satisfying.  I'll look a bit, and see if we can unify things a bit.

Comment (shinrich) [reply proxy/http2/Http2Stream.cc]: I have a different fix that I'm running on a prod box for 30 minutes (a new record!).  I made a change in release_stream.  It was removing the stream from the connection_state.  This means that the actual delete_stream would exit immediately without cleaning up the priority tree.  

I must run out right now, but I'll put up another PR later this evening. Assuming the prod box doesn't go crazy before.

Comment (shinrich) [reply proxy/http2/Http2Stream.cc]: My fix is in PR #2781

**Comment by maskit** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Testing on Docs now.

**Comment by zwoop** [comment]
Cherry-picked to 7.1.2.
