### PR TITLE
fix race condition with session thread migration

### LINKED ISSUE #9690: ats92/master crash
stack trace ats92 (9df7f8d4d41bda93e1d1a3ba741a6bce53c64ef0)
live linear cache ram drives only, testing session mutex congestion.  Turned on http_ss debug but also for fun made a custom debug tag with session lifetime information which also causes the same crash.

Note CacheVC::openReadFromWriterFailure, failure to attach read while writer.

```
#0  0x00007f1ecdf44aff in raise () from /lib64/libc.so.6
#1  0x00007f1ecdf17ea5 in abort () from /lib64/libc.so.6
#2  0x00007f1ed040cace in ink_abort (
    message_format=0x7f1ed0479fc8 "%s:%d: failed assertion `%s`")
    at ink_error.cc:99
#3  0x00007f1ed04083cb in _ink_assert (
    expression=0xb0e2f5 "!new_hdr->valid()", 
    file=0xb0e268 "HttpTransactHeaders.cc", line=209) at ink_assert.cc:37
#4  0x000000000083437f in HttpTransactHeaders::copy_header_fields (
    src_hdr=0x7f1e593a55a0, new_hdr=0x7f1e593a5620, 
    retain_proxy_auth_hdrs=false, date=0) at HttpTransactHeaders.cc:209
#5  0x0000000000825147 in HttpTransact::build_request (s=0x7f1e593a4ef8, 
    base_request=0x7f1e593a55a0, outgoing_request=0x7f1e593a5620, 
    outgoing_version=...) at HttpTransact.cc:7767
#6  0x000000000080c601 in HttpTransact::HandleCacheOpenReadMiss (
    s=0x7f1e593a4ef8) at HttpTransact.cc:3367
#7  0x0000000000805479 in HttpTransact::HandleCacheOpenRead (s=0x7f1e593a4ef8)
    at HttpTransact.cc:2440
#8  0x00000000007dad12 in HttpSM::call_transact_and_set_next_state (
    this=0x7f1e593a4df0, f=0x0) at HttpSM.cc:7589
#9  0x00000000007bbc15 in HttpSM::handle_api_return (this=0x7f1e593a4df0)
    at HttpSM.cc:1706
#10 0x00000000007bb90b in HttpSM::state_api_callout (this=0x7f1e593a4df0, 
    event=0, data=0x0) at HttpSM.cc:1638
#11 0x00000000007d10b1 in HttpSM::do_api_callout_internal (this=0x7f1e593a4df0)
    at HttpSM.cc:5555
#12 0x00000000007e4fc3 in HttpSM::do_api_callout (this=0x7f1e593a4df0)
    at HttpSM.cc:421
#13 0x00000000007e500a in HttpSM::setup_cache_lookup_complete_api (
    this=0x7f1e593a4df0) at HttpSM.cc:2648
#14 0x00000000007c1cf8 in HttpSM::state_cache_open_read (this=0x7f1e593a4df0, 
    event=1103, data=0xffffffffffffb04f) at HttpSM.cc:2709
#15 0x00000000007c2190 in HttpSM::main_handler (this=0x7f1e593a4df0, 
    event=1103, data=0xffffffffffffb04f) at HttpSM.cc:2753
#16 0x00000000007186f1 in Continuation::handleEvent (this=0x7f1e593a4df0, 
    event=1103, data=0xffffffffffffb04f)
    at /home/bolsen149/git/tsb-ats92/src/ats/iocore/eventsystem/I_Continuation.h:227
#17 0x00000000008574b5 in HttpCacheSM::state_cache_open_read (
    this=0x7f1e593a6c18, event=1103, data=0xffffffffffffb04f)
    at HttpCacheSM.cc:128
#18 0x00000000007186f1 in Continuation::handleEvent (this=0x7f1e593a6c18, 
    event=1103, data=0xffffffffffffb04f)
    at /home/bolsen149/git/tsb-ats92/src/ats/iocore/eventsystem/I_Continuation.h:227
#19 0x00000000009ab64d in CacheVC::openReadFromWriterFailure (this=
    0x7f1e80caf200, event=1103, e=0xffffffffffffb04f) at CacheRead.cc:189
#20 0x00000000009ac521 in CacheVC::openReadFromWriter (this=0x7f1e80caf200, 
    event=2, e=0x7f1d145e39c0) at CacheRead.cc:348
#21 0x00000000007186f1 in Continuation::handleEvent (this=0x7f1e80caf200, 
    event=2, data=0x7f1d145e39c0)
    at /home/bolsen149/git/tsb-ats92/src/ats/iocore/eventsystem/I_Continuation.h:227
#22 0x0000000000acd599 in EThread::process_event (this=0x7f1ecc5da010, 
    e=0x7f1d145e39c0, calling_code=2) at UnixEThread.cc:164
#23 0x0000000000acdb04 in EThread::execute_regular (this=0x7f1ecc5da010)
    at UnixEThread.cc:273
#24 0x0000000000acde6b in EThread::execute (this=0x7f1ecc5da010)
    at UnixEThread.cc:364
#25 0x0000000000acc628 in spawn_thread_internal (a=0x1455350) at Thread.cc:91
#26 0x00007f1ecedf71cf in start_thread () from /lib64/libpthread.so.0
#27 0x00007f1ecdf2fe73 in clone () from /lib64/libc.so.6

```

### PR DESCRIPTION
**Pull request by traeak**
This is a fix for a race condition (found and debugged in ats92) when a session is taken from the session pool and migrated to another thread.  This is with GLOBAL session pools.  There are still rare cases where events are still leaking through to the VC in the pre-migrated thread causing various different asserts.

This PR moves thread migration out of the session manager acquire critical section and locks and stops events on the original thread netvc during migration.  Global (and likely hybrid) pool performance is improved in this case.

Initial testing using test case verifies that ats master crashes (quickly and a lot) without the patch and runs fine the patch.

Will test in prod for stability.

should close #9690 

Also related to: https://github.com/apache/trafficserver/issues/9689

### CODE REVIEW

File: src/proxy/http/HttpSessionManager.cc [hunk 1]
```diff
@@ -440,57 +441,66 @@ HttpSessionManager::_acquire_session(sockaddr const *ip, CryptoHash const &hostn
...
+      if (nullptr != to_return) {
+        server_vc = dynamic_cast<UnixNetVConnection *>(to_return->get_netvc());
+        if (nullptr != server_vc) {
+          // Keep things from timing out on us
+          server_vc->set_inactivity_timeout(server_vc->get_inactivity_timeout());
+
+          // If thread must be migrated, clear out the VC's
+          // data and event handling on the original thread.
+          if (ethread != server_vc->get_thread()) {
+            SCOPED_MUTEX_LOCK(vclock, server_vc->mutex, ethread);
```
Comment (shinrich) [inline src/proxy/http/HttpSessionManager.cc:456]: Do you want to do a try-lock instead?  If the other thread handles a close before you get the lock here, things could disappear from underneath?

**Comment by traeak** [comment]
Current proposed fix will drop 1-2 bytes from the content body instead of aborting.

**Comment by JosiahWI** [comment]
[approve ci]

File: src/proxy/http/HttpSessionManager.cc [hunk 2]
```diff
@@ -151,52 +151,58 @@ ServerSessionPool::acquireSession(sockaddr const *addr, CryptoHash const &hostna
...
     in_port_t port = ats_ip_port_cast(addr);
-    auto first     = m_fqdn_pool.find(hostname_hash);
-    while (first != m_fqdn_pool.end() && first->hostname_hash == hostname_hash) {
-      Debug("http_ss", "Compare port 0x%x against 0x%x", port, ats_ip_port_cast(first->get_remote_addr()));
-      if (port == ats_ip_port_cast(first->get_remote_addr()) &&
-          (!(match_style & TS_SERVER_SESSION_SHARING_MATCH_MASK_SNI) || validate_sni(sm, first->get_netvc())) &&
-          (!(match_style & TS_SERVER_SESSION_SHARING_MATCH_MASK_HOSTSNISYNC) || validate_host_sni(sm, first->get_netvc())) &&
-          (!(match_style & TS_SERVER_SESSION_SHARING_MATCH_MASK_CERT) || validate_cert(sm, first->get_netvc()))) {
-        zret = HSM_DONE;
+    auto iter      = m_fqdn_pool.find(hostname_hash);
```
Comment (cmcfarlen) [inline src/proxy/http/HttpSessionManager.cc:154]: I noticed this iter variable is re-declared below. This is a nitpick, but it makes it harder to reason about the scope of this variable with the other one introduced.

Comment (traeak) [reply src/proxy/http/HttpSessionManager.cc]: There are 2 different scopes, the iterators are different types (perhaps kill the auto and make it more explicit?).  Generally I only renamed "first" to "iter", and then moved the confusing zret logic down to the bottom of the function.

**Review by shinrich — APPROVED** [review]
The logic looks clean to me.
