### PR TITLE
BoringSSL doesn't have BIO_sock_non_fatal_error()

### LINKED ISSUE #1437: Build fail with BoringSSL
I'm trying build TS with BoringSSL, but I got this.

```
BIO_fastopen.cc:76:9: error: use of undeclared identifier 'BIO_sock_non_fatal_error'
    if (BIO_sock_non_fatal_error(errno)) {
        ^
BIO_fastopen.cc:99:9: error: use of undeclared identifier 'BIO_sock_non_fatal_error'
    if (BIO_sock_non_fatal_error(errno)) {
        ^
2 errors generated.
```

BoringSSL doesn't have `BIO_sock_non_fatal_error`. `bio_fd_non_fatal_error` looks similar API, but it is internal API.

### PR DESCRIPTION
**Pull request by jablko**
Fixes #1437

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1516/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1410/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/81/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1411/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1517/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/82/ for details.

File: iocore/net/BIO_fastopen.cc [hunk 1]
```diff
@@ -27,6 +27,67 @@
 
 #include "BIO_fastopen.h"
 
+// For BoringSSL, which for some reason doesn't have this function.
+// (In BoringSSL, sock_read() and sock_write() use the internal
+// bio_fd_non_fatal_error() instead.) #1437
+//
+// The following is copied from
+// https://github.com/openssl/openssl/blob/3befffa39dbaf2688d823fcf2bdfc07d2487be48/crypto/bio/bss_sock.c
```
Comment (masaori335) [inline iocore/net/BIO_fastopen.cc]: It looks like we need to add "OpenSSL License" in LICENSE file, because this is just copy.
(Sorry for I should have noticed this before merge)

Comment (masaori335) [inline iocore/net/BIO_fastopen.cc]: How about just add a function like this? We don't support WINDOWS and don't need those "#ifdef". Just checking error codes looks enough.
```
static int
non_fetal_error(int err)
{
  if (err == EWOULDBLOCK || err == ENOTCONN || err == EINTR || err == EAGAIN || err == EPROTO || err == EINPROGRESS || err == EALREADY) {
    return 1;
  }
  return 0;
}
```

**Comment by zwoop** [comment]
Did we add the necessary attribution to NOTICES files? If not, please do so.

File: iocore/net/BIO_fastopen.cc (hunk 1 above)
Comment (jablko) [inline iocore/net/BIO_fastopen.cc]: That works ... Is the purpose to avoid having to attribute it?

In general, I like to code for OpenSSL, and add fixes to make other environments conform to it -- unless there's a reason not to. So in this case I'd continue calling BIO_sock_non_fatal_error(), and copy it verbatim from OpenSSL if it's missing.

Functionally, your solution is equivalent (and cleaner!), but unless there's a reason not to use OpenSSL's function, that's the style I prefer. I'm happy either way, though :-)

I'll open a PR to add attribution to the NOTICE file.

Comment (masaori335) [inline iocore/net/BIO_fastopen.cc]: I understood. Let's add the attribution to the NOTICE file and use code from OpenSSL.
