### PR TITLE
Fix build issues in H3 unit tests

### LINKED ISSUE #9302: quiche make check build failure
I added a quiche branch build job for 10-Dev. It looks like `make check` fails compilation:
https://ci.trafficserver.apache.org/view/10-Dev/job/10-Dev/job/quiche/2/

```
In file included from ./test/test_QPACK.cc:31:
./../../iocore/net/quic/Mock.h:656:3: error: 'virtual QUICRTTProvider* MockQUICContext::rtt_provider() const' marked 'override', but does not override
  656 |   rtt_provider() const override
      |   ^~~~~~~~~~~~
./../../iocore/net/quic/Mock.h:662:3: error: 'virtual QUICPacketProtectionKeyInfo* MockQUICContext::key_info() const' marked 'override', but does not override
  662 |   key_info() const override
      |   ^~~~~~~~
./../../iocore/net/quic/Mock.h:668:3: error: 'virtual QUICLDConfig& MockQUICContext::ld_config() const' marked 'override', but does not override
  668 |   ld_config() const override
      |   ^~~~~~~~~
./../../iocore/net/quic/Mock.h:674:3: error: 'virtual QUICCCConfig& MockQUICContext::cc_config() const' marked 'override', but does not override
  674 |   cc_config() const override
      |   ^~~~~~~~~
./../../iocore/net/quic/Mock.h:680:3: error: 'virtual QUICPathManager* MockQUICContext::path_manager() const' marked 'override', but does not override
  680 |   path_manager() const override
      |   ^~~~~~~~~~~~
make[3]: *** [Makefile:1143: test/test_qpack-test_QPACK.o] Error 1

```

## Steps for Reproduction

* docker image: ci.trafficserver.apache.org/ats/rockylinux:8 
* Branch: 10-Dev
* configure: `/configure --enable-experimental-plugins --enable-example-plugins --with-quiche=/opt/quiche --prefix=/tmp/ats --enable-werror --enable-debug`
* `make -j4 && make install && make -j4 check`

### PR DESCRIPTION
**Pull request by maskit**
This fixes #9302

### CODE REVIEW

File: iocore/net/quic/Mock.h [hunk 1]
```diff
@@ -246,6 +255,8 @@ class MockQUICStreamManager : public QUICStreamManagerImpl
   MockQUICStreamManager(QUICContext *context) : QUICStreamManagerImpl(context, nullptr) {}
 
   // Override
+#if HAVE_QUICHE_H
+#else
```
Comment (bneradt) [inline iocore/net/quic/Mock.h:259]: Maybe: `#ifndef HAVE_QUICHE_H`?

File: iocore/net/quic/Mock.h [hunk 2]
```diff
@@ -652,6 +664,8 @@ class MockQUICContext : public QUICContext
   {
     return _config;
   }
+#if HAVE_QUICHE_H
+#else
```
Comment (bneradt) [inline iocore/net/quic/Mock.h:668]: `#ifndef HAVE_QUICHE_H`

**Review by bneradt — CHANGES_REQUESTED** [review]
Thanks for addressing the warnings.

**Review by bneradt — APPROVED** [review]
