### PR TITLE
handle transport of empty body response

### LINKED ISSUE #2887: In Lua plugin, response transform hook hangs indefinitely if the response contents are empty
- ATS Version: 7.1 (compiled using `--enable-experimental-plugins`)
- Debian Jessie within Docker 17.11

**Lua plugin:**
```
function transform_response(data, eos)
    ts.debug("transform_response") -- Never printed
    return data, eos
end

function do_global_txn_start()
    ts.hook(TS_LUA_RESPONSE_TRANSFORM, transform_response)
    return 0
end
```

**Steps to reproduce:**

1. Configure ATS using the lua plugin above
2. Make forward proxy request to an http page with 0 byte body
3. Request hangs forever, `transform_response` is never invoked

### PR DESCRIPTION
**Pull request by shukitchan**
This fixes #2887. 
The downstream VIO is not re-enabled in this corner case. The fix also allows a lua function to be called so we can even transform an empty string response body. 

@utkuzih pls take a look and see if it handles your use case correctly.

### CODE REVIEW

**Comment by utkuzih** [comment]
Works well.

I got `transform_response("", 1)` call right away. Also, I got the following additional log: `[ts_lua_transform_handler] no input VIO and output VIO`.

File: plugins/experimental/ts_lua/ts_lua_transform.c [hunk 1]
```diff
@@ -86,15 +86,22 @@ ts_lua_transform_handler(TSCont contp, ts_lua_http_transform_ctx *transform_ctx,
...
+    } else {
+      TSDebug(TS_LUA_DEBUG_TAG, "[%s] no input VIO and output VIO", __FUNCTION__);
+      empty_input = 1;
     }
-    return 0;
   }
 
-  input_reader = TSVIOReaderGet(input_vio);
+  if (empty_input == 0) {
+    input_reader = TSVIOReaderGet(input_vio);
```
Comment (SolidWallOfCode) [inline plugins/experimental/ts_lua/ts_lua_transform.c]: `input_reader` is in indeterminate state if `empty_input`?

File: plugins/experimental/ts_lua/ts_lua_transform.c [hunk 2]
```diff
@@ -103,18 +110,29 @@ ts_lua_transform_handler(TSCont contp, ts_lua_http_transform_ctx *transform_ctx,
     transform_ctx->reserved.buffer = TSIOBufferCreate();
     transform_ctx->reserved.reader = TSIOBufferReaderAlloc(transform_ctx->reserved.buffer);
 
-    transform_ctx->upstream_bytes   = TSVIONBytesGet(input_vio);
+    if (empty_input == 0) {
```
Comment (SolidWallOfCode) [inline plugins/experimental/ts_lua/ts_lua_transform.c]: I'd be more tempted to use ternary operators in these cases, since the key is that something is always assigned. E.g.
```
transform_ctx->upstream_bytes = empty_input ? 0 : TSVIONBytesGets(input_vio);
```

File: plugins/experimental/ts_lua/ts_lua_transform.c [hunk 3]
```diff
@@ -140,30 +162,38 @@ ts_lua_transform_handler(TSCont contp, ts_lua_http_transform_ctx *transform_ctx,
...
+        lua_pushinteger(L, 1); /* second param, data finished */
+      } else {
+        lua_pushinteger(L, 0); /* second param, data not finish */
+      }
     } else {
-      lua_pushlstring(L, start, (size_t)towrite);
-      TSIOBufferReaderConsume(transform_ctx->reserved.reader, towrite);
-      towrite = 0;
-    }
+      lua_pushlightuserdata(L, transform_ctx);
```
Comment (SolidWallOfCode) [inline plugins/experimental/ts_lua/ts_lua_transform.c]: Couldn't this
```
lua_pushlightuserdata(L, transform_ctx);		 +
lua_rawget(L, LUA_GLOBALSINDEX);
```
be left promoted out of the `if`?

File: plugins/experimental/ts_lua/ts_lua_transform.c [hunk 4]
```diff
@@ -140,30 +162,38 @@ ts_lua_transform_handler(TSCont contp, ts_lua_http_transform_ctx *transform_ctx,
...
-    lua_pushlightuserdata(L, transform_ctx);
-    lua_rawget(L, LUA_GLOBALSINDEX); /* push function */
+    if (empty_input == 0) {
+      blk   = TSIOBufferReaderStart(transform_ctx->reserved.reader);
+      start = TSIOBufferBlockReadStart(blk, transform_ctx->reserved.reader, &blk_len);
+
+      lua_pushlightuserdata(L, transform_ctx);
+      lua_rawget(L, LUA_GLOBALSINDEX); /* push function */
+
+      if (towrite > blk_len) {
```
Comment (SolidWallOfCode) [inline plugins/experimental/ts_lua/ts_lua_transform.c]: Could you clip `towrite` to `blk_len` here and avoid the more complex `if`? You might be able to blend the `empty_input` case in as well, since `towrite == 0` and `eos = 1` in that case already, you just need to avoid touching `reserved.reader`. Even if `start` is `NULL`, it shouldn't matter because the length is `0` (although `start` could be initialized to `""` just as easily).

File: plugins/experimental/ts_lua/ts_lua_transform.c [hunk 5]
```diff
@@ -231,13 +261,19 @@ ts_lua_transform_handler(TSCont contp, ts_lua_http_transform_ctx *transform_ctx,
   if (toread > input_avail) { // upstream not finished.
     if (eos) {
       TSVIONBytesSet(transform_ctx->output.vio, transform_ctx->total);
-      TSContCall(TSVIOContGet(input_vio), TS_EVENT_VCONN_EOS, input_vio);
+      if (empty_input == 0) {
+        TSContCall(TSVIOContGet(input_vio), TS_EVENT_VCONN_EOS, input_vio);
```
Comment (SolidWallOfCode) [inline plugins/experimental/ts_lua/ts_lua_transform.c]: You can't `TSContCall` here for `empty_input == 1` because there's no `input_vio`? But that seems to be set early in the function. It might be reasonable to send `TS_EVENT_VCONN_EOS` for empty input.

**Comment by SolidWallOfCode** [comment]
I had some style questions, but overall it looks reasonable.

File: plugins/experimental/ts_lua/ts_lua_transform.c (hunk 5 above)
Comment (shukitchan) [reply plugins/experimental/ts_lua/ts_lua_transform.c]: I find that it is not needed in this case.
