### PR TITLE
Removes the abort() from header_rewrite, and try to deal with errors

### LINKED ISSUE #2424: header_rewrite crash if regex malformed
I managed to crash ATS with a header_rewrite config:

cond %{REMAP_PSEUDO_HOOK} [AND]
cond %{IP:CLIENT} /(1.2.3.4|127.0.0.1|^10\./ [NOT]
    set-status 403

(note the missing ")" in the IP:CLIENT regex).

ATS went into a crash loop with this traffic log
traffic_manager[29290]: {0x7f3043b1c840} NOTE: [LocalManager::pollMgmtProcessServer] Server Process terminated due to Sig 6: Aborted

Putting in the missing ")" stopped the loop.

Would be better to not crash, but, instead, throw a log error and not load the config.

### PR DESCRIPTION
**Pull request by zwoop**
Bryan suggested using exceptions here, rather than just producing errors
    in the log files. As ugly as it is, it does seem to work ... But I blame
    him for all future issues! Long term, I think it'd be better to eliminate
    the exceptions here, and fix all the various layers of returning and
    perculating errors all the way back up through the stack.

Closes #2424

### CODE REVIEW

**Comment by shukitchan** [comment]
looks good.

File: plugins/header_rewrite/header_rewrite.cc [hunk 1]
```diff
@@ -222,16 +223,21 @@ RulesConfig::parse_config(const std::string &fname, TSHttpHookID default_hook)
...
-        delete rule;
-        return false;
-      }
-    } else {
-      if (!rule->add_operator(p, filename.c_str(), lineno)) {
-        delete rule;
-        return false;
+    // This is pretty ugly, but it turns out, some conditions / operators can fail (regexes), which didn't use to be the case.
+    // Long term, maybe we need to perculate all this up through add_condition() / add_operator() rather than this big ugly try.
+    try {
```
Comment (bryancall) [inline plugins/header_rewrite/header_rewrite.cc]: Try and catch?  What the hell are you doing?  :)


j/k - I am OK with it considering the alternative.

File: plugins/header_rewrite/header_rewrite.cc [hunk 2]
```diff
@@ -222,16 +223,21 @@ RulesConfig::parse_config(const std::string &fname, TSHttpHookID default_hook)
...
+      if (p.is_cond()) {
+        if (!rule->add_condition(p, filename.c_str(), lineno)) {
+          throw std::runtime_error("add_condition() failed");
+        }
+      } else {
+        if (!rule->add_operator(p, filename.c_str(), lineno)) {
+          throw std::runtime_error("add_operator() failed");
+        }
       }
+    } catch (std::runtime_error &e) {
```
Comment (randall) [inline plugins/header_rewrite/header_rewrite.cc]: Should you log the log exception here?

File: plugins/header_rewrite/header_rewrite.cc [hunk 3]
```diff
@@ -222,16 +223,21 @@ RulesConfig::parse_config(const std::string &fname, TSHttpHookID default_hook)
...
-      if (!rule->add_condition(p, filename.c_str(), lineno)) {
-        delete rule;
-        return false;
-      }
-    } else {
-      if (!rule->add_operator(p, filename.c_str(), lineno)) {
-        delete rule;
-        return false;
+    // This is pretty ugly, but it turns out, some conditions / operators can fail (regexes), which didn't use to be the case.
+    // Long term, maybe we need to perculate all this up through add_condition() / add_operator() rather than this big ugly try.
```
Comment (randall) [inline plugins/header_rewrite/header_rewrite.cc]: percolate

**Comment by zwoop** [comment]
Issues fixed, @randall @bryancall Please review again.

**Comment by zwoop** [comment]
Cherry-picked to 8.1.x
