### PR TITLE
Fix log filters for IP conditions.

### LINKED ISSUE #6405: LogFilterIP appears to be broken
Using a simple log filter condition like `%<chi> MATCH 127.0.0.1` doesn't ever match, so LogFilterIP::toss_entry always tosses the log line as it's being reported by the debug log:
```
Feb 07 13:28:13 traffic-cache-atstext traffic_manager[8927]: [Feb  7 13:28:13.466] {0x2adf1ea94700} DEBUG: <LogObject.cc:555 (log)> (log) entry filtered, skipping ...
```

it looks like `LogFilterIP::is_match` https://github.com/apache/trafficserver/blob/master/proxy/logging/LogFilter.cc#L831-L844 needs to be fixed.

### PR DESCRIPTION
**Pull request by bneradt**
Our log filter mechanism for IP addresses did not compare the filter's
specified IP address with the log field's IP address correctly. This
fixes that matching mechanism.

Fixes #6405

### CODE REVIEW

**Review by traeak — APPROVED** [review]
This all looks fine.

File: proxy/logging/LogFilter.cc [hunk 1]
```diff
@@ -833,11 +833,17 @@ LogFilterIP::is_match(LogAccess *lad)
...
+    m_field->marshal(lad, reinterpret_cast<char *>(&field_ip_storage));
+
+    // Convert to the IpAddr type that the map holds.
+    IpAddr field_ip;
+    if (field_ip_storage._ip._family == AF_INET) {
+      field_ip = field_ip_storage._ip4._addr;
+    } else if (field_ip_storage._ip._family == AF_INET6) {
+      field_ip = field_ip_storage._ip6._addr;
+    }
+    zret = m_map.contains(reinterpret_cast<IpAddr &>(field_ip));
```
Comment (SolidWallOfCode) [inline proxy/logging/LogFilter.cc:846]: Why are you casting an `IpAddr` to an `IpAddr`?

Comment (bneradt) [reply proxy/logging/LogFilter.cc:846]: Ah, yeah. Left over from the previous version of this that had to cast from the storage type.

Comment (bneradt) [reply proxy/logging/LogFilter.cc:846]: https://github.com/apache/trafficserver/pull/8259
