### PR TITLE
Set END_STREAM flag when write_vio ntodo is 0

### LINKED ISSUE #6178: ATS9: performance regression
Just synced our internal test branch with the open source 9.0.x branch.  When I installed the resulting package on our canary production box, the average response latency more than doubled from around 120ms to over 450ms.

Running my python analysis script over squid.log files with the previous build and the new build show that the change is in HTTP/2 transactions.

Previous build H2 stats
```
total 1203448 entrys 50%=27 80%=146 90%=304 95%=464 99%=1054 max=%858135
```
New build H2 stats
```
total 561087 entrys 50%=26 80%=193 90%=417 95%=1670 99%=9980 max=%857883
```

If I revert  @masaori335's commit 2baa388c3e3cb3ff71c468c8b0b4c68d8a0320fe, then the average latency goes back down.

### PR DESCRIPTION
**Pull request by masaori335**
Another approach to fix #6178.

### CODE REVIEW

File: proxy/http2/Http2ConnectionState.cc [hunk 1]
```diff
@@ -1584,7 +1584,7 @@ Http2ConnectionState::send_headers_frame(Http2Stream *stream)
   if (header_blocks_size <= static_cast<uint32_t>(BUFFER_SIZE_FOR_INDEX(buffer_size_index[HTTP2_FRAME_TYPE_HEADERS]))) {
     payload_length = header_blocks_size;
     flags |= HTTP2_FLAGS_HEADERS_END_HEADERS;
-    if (h2_hdr.presence(MIME_PRESENCE_CONTENT_LENGTH) && h2_hdr.get_content_length() == 0) {
+    if ((h2_hdr.presence(MIME_PRESENCE_CONTENT_LENGTH) && h2_hdr.get_content_length() == 0) || stream->is_body_done()) {
```
Comment (masaori335) [inline proxy/http2/Http2ConnectionState.cc]: `Http2Stream::is_body_done()` returns `true` when `Http2Stream::write_vio.ntodo()` is 0.
If this approach goes well, this should be renamed to avoid confusion.

**Comment by masaori335** [comment]
It looks like simple check of `write_vio.ntodo()` makes a problem with `100 Continue` response for the POST request with `expect: 100-continue` header.

**Comment by masaori335** [comment]
The issue with 100 Continue response looks exists regardless of the dechunk cleanup changes. Filed as #6202.

**Comment by masaori335** [comment]
100 continue issue is addressed with new commit.

**Comment by shinrich** [comment]
Will set up a performance build too.

**Comment by shinrich** [comment]
My test build on a prod box is looking good so far with respect to latency.  Average latency staying around 120ms.  I'll build an official build tomorrow so I'm certain that I'm running the right thing.  But so far, so good.

**Comment by masaori335** [comment]
Pushed new commits. Logics are almost the same as before. 

- Now, this PR depends on #6209.
- Add a test case (using "204 No Content" instead of "304 Not Modified" to make it easy)

**Comment by zwoop** [comment]
Oops, since there were two commits here, I missed one. I've cherry-picked both of these to the v9.0.x branch.
