### PR TITLE
H2 Assertsion at Http2DependencyTree::deactivate

### LINKED ISSUE #2208: H2 Assert fails sometimes at Http2DependencyTree::deactivate
This happens sometimes when I terminate h2load after running it for a while.

```
[Jun 28 15:52:56.177] Server {0xb0004000} DEBUG: <Http2ClientSession.cc:254 (do_io_close)> (http2_cs) [0] session closed
[Jun 28 15:52:56.177] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:1114 (delete_stream)> (http2_con) [0] [199] Delete stream
[Jun 28 15:52:56.177] Server {0xb000a000} DEBUG: <Http2ClientSession.cc:254 (do_io_close)> (http2_cs) [1] session closedFatal: ./Http2DependencyTree.h:319: failed assertion `node->parent->queue->top() == node->entry`

2017-06-28 15:52:56.177736+0900 traffic_server[67848:12159540] Fatal: ./Http2DependencyTree.h:319: failed assertion `node->parent->queue->top() == node->entry`
[Jun 28 15:52:56.177] Server {0xb000a000} DEBUG: <Http2ConnectionState.cc:1114 (delete_stream)> (http2_con) [1] [199] Delete stream
Process 67848 stopped
* thread #5, name = '[ET_NET 11]', stop reason = signal SIGABRT
    frame #0: 0x000000000060bd42 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x60bd42 <+10>: jae    0x60bd4c                  ; <+20>
    0x60bd44 <+12>: movq   %rax, %rdi
    0x60bd47 <+15>: jmp    0x604caf                  ; cerror_nocancel
    0x60bd4c <+20>: retq   
(lldb) bt
* thread #5, name = '[ET_NET 11]', stop reason = signal SIGABRT
  * frame #0: 0x000000000060bd42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x0000000000753457 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x000000000053d420 libsystem_c.dylib`abort + 129
    frame #3: 0x000000000002a160 libtsutil.8.dylib`ink_abort(message_format="%s:%d: failed assertion `%s`") at ink_error.cc:99
    frame #4: 0x000000000002703f libtsutil.8.dylib`::_ink_assert(expression="node->parent->queue->top() == node->entry", file="./Http2DependencyTree.h", line=319) at ink_assert.cc:37
    frame #5: 0x00000001001a4880 traffic_server`Http2DependencyTree<Http2Stream*>::deactivate(this=0x0000000000c0f080, node=0x0000000005c04030, sent=0) at Http2DependencyTree.h:319
    frame #6: 0x00000001001a473d traffic_server`Http2ConnectionState::delete_stream(this=0x0000000000ef9e58, stream=0x000000000d7073e0) at Http2ConnectionState.cc:1120
    frame #7: 0x00000001001a2bb6 traffic_server`Http2ConnectionState::cleanup_streams(this=0x0000000000ef9e58) at Http2ConnectionState.cc:1089
    frame #8: 0x00000001001a132b traffic_server`Http2ConnectionState::main_event_handler(this=0x0000000000ef9e58, event=2252, edata=0x0000000000ef9c00) at Http2ConnectionState.cc:873
    frame #9: 0x000000010001e0b0 traffic_server`Continuation::handleEvent(this=0x0000000000ef9e58, event=2252, data=0x0000000000ef9c00) at I_Continuation.h:153
    frame #10: 0x000000010019e5cc traffic_server`send_connection_event(cont=0x0000000000ef9e58, event=2252, edata=0x0000000000ef9c00) at Http2ClientSession.cc:58
    frame #11: 0x000000010019f0a4 traffic_server`Http2ClientSession::do_io_close(this=0x0000000000ef9c00, alerrno=-1) at Http2ClientSession.cc:257
    frame #12: 0x000000010019dc31 traffic_server`Http2ClientSession::main_event_handler(this=0x0000000000ef9c00, event=3, edata=0x00000000038acea8) at Http2ClientSession.cc:324
    frame #13: 0x000000010001e0b0 traffic_server`Continuation::handleEvent(this=0x0000000000ef9c00, event=3, data=0x00000000038acea8) at I_Continuation.h:153
    frame #14: 0x0000000100318878 traffic_server`write_signal_and_update(event=3, vc=0x00000000038acd00) at UnixNetVConnection.cc:155
    frame #15: 0x0000000100318a8d traffic_server`write_signal_done(event=3, nh=0x0000000003406bf0, vc=0x00000000038acd00) at UnixNetVConnection.cc:197
    frame #16: 0x0000000100318681 traffic_server`write_signal_error(nh=0x0000000003406bf0, vc=0x00000000038acd00, lerrno=-61486120) at UnixNetVConnection.cc:216
    frame #17: 0x00000001003182d2 traffic_server`write_to_net_io(nh=0x0000000003406bf0, vc=0x00000000038acd00, thread=0x0000000003403000) at UnixNetVConnection.cc:534
    frame #18: 0x0000000100317a65 traffic_server`write_to_net(nh=0x0000000003406bf0, vc=0x00000000038acd00, thread=0x0000000003403000) at UnixNetVConnection.cc:400
    frame #19: 0x000000010030ba83 traffic_server`NetHandler::mainNetEvent(this=0x0000000003406bf0, event=5, e=0x000000000104c640) at UnixNet.cc:514
    frame #20: 0x000000010001e0b0 traffic_server`Continuation::handleEvent(this=0x0000000003406bf0, event=5, data=0x000000000104c640) at I_Continuation.h:153
    frame #21: 0x000000010033da75 traffic_server`EThread::process_event(this=0x0000000003403000, e=0x000000000104c640, calling_code=5) at UnixEThread.cc:122
    frame #22: 0x000000010033e2da traffic_server`EThread::execute(this=0x0000000003403000) at UnixEThread.cc:266
    frame #23: 0x000000010033ce0c traffic_server`spawn_thread_internal(a=0x000000000092db00) at Thread.cc:91
    frame #24: 0x000000000075093b libsystem_pthread.dylib`_pthread_body + 180
    frame #25: 0x0000000000750887 libsystem_pthread.dylib`_pthread_start + 286
    frame #26: 0x000000000075008d libsystem_pthread.dylib`thread_start + 13
```

### PR DESCRIPTION
**Pull request by scw00**
Fixed #2208 

H2 Assert fails sometimes at Http2DependencyTree::deactivate.

There is a problem, when we received the reprioritize frame. The priority queue will be changed.
This event will happen again, when client abort.

<b>This pr only fixes the trigger by h2load</b>.

By the way,  @masaori335 why do we use this assertion? :-)

### CODE REVIEW

**Comment by scw00** [comment]
The priority queue's entry is in chronological order,  `Queue` is better than `DLL` if we try to remove the bottom entry (actually, it is first one in the list).

**Comment by masaori335** [comment]
The assertion assumes when ATS deactivate a node, it's the top node of priority tree.
But it looks like it's wrong when ATS delete streams. Because ATS pickup a stream from stream list not from priority tree.
So, I think just removing the assertion is fine.

**Comment by masaori335** [comment]
I'm fine to change the data structure of stream_list from `DLL` to `Queue`. But as you said, this will fix only h2load case. 
If TS needs to close a stream by some error and the stream is not top node of priority queue, this assertion will be occur.

File: proxy/http2/Http2Stream.h [hunk 1]
```diff
@@ -153,7 +153,7 @@ class Http2Stream : public ProxyClientTransaction
   ssize_t client_rwnd;
   ssize_t server_rwnd = Http2::initial_window_size;
 
-  LINK(Http2Stream, link);
+  // LINK(Http2Stream, link);
```
Comment (masaori335) [inline proxy/http2/Http2Stream.h]: Please remove unused code. BTW, I'm surprised that `Continuation` has LINK macro and we don't need this :D

**Comment by scw00** [comment]
@masaori335 Thanks for reviewing. As you comment above, I remove the unused code ! Can you please review again?

**Comment by maskit** [comment]
I'd rather use C++ style casts (e.g. static_cast).

**Comment by scw00** [comment]
Thanks, I'll updated later !

**Comment by scw00** [comment]
@masaori335 @maskit updated! Please review again !

**Comment by scw00** [comment]
@masaori335 @maskit updated! Please review again !

**Comment by zwoop** [comment]
@masaori335 Is this a candidate for a v7.1.1 release ? If so, please add it to the 7.x project.

**Comment by masaori335** [comment]
- Why this is a candidate for 7.x
  - To make HTTP/2 Priority Feature correct
  - To later backport easier, because the data structure of stream_list is changed
- Which version(s) of 7.x it should go to. 
  - v7.1.1

**Comment by zwoop** [comment]
Cool. I'm testing latest master on Docs (with this patch) right now. However, this does not cherry-pick cleanly to the 7.1.x branch, so can you please make a PR against that branch as well?
