### PR TITLE
Send HPACK dynamic table size update at the beginning of header block

### LINKED ISSUE #1591: Advertised header table size is not used
Current H2 implementation doesn't use the advertised header table size.

To reproduce:
```
$ nghttp -nv -c 1024 https://localhost/
```

This fails with COMPRESSION_ERROR.

Todo:
- Update internal maximum header table size with advertised size (SETTINGS_HEADER_TABLE_SIZE).
- Send "Dynamic Table Size Update" in the beginning of a header block

### PR DESCRIPTION
**Pull request by maskit**
This closes #1591.

There are two commits. The first one is a bug fix for the table size update issue. The second commit adds an implementation limit to avoid abusing. The maximum table size is advertised by clients, but we can use any value lower than the value. The value 64k is came from major client implementations.
https://bugzilla.mozilla.org/show_bug.cgi?id=1296280
https://bugs.chromium.org/p/chromium/issues/detail?id=642784

 I will squash the commits before merging.

### CODE REVIEW

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/273/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/259/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/255/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/384/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1954/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1846/

File: proxy/http2/HTTP2.cc [hunk 1]
```diff
@@ -597,10 +597,17 @@ http2_generate_h2_header_from_1_1(HTTPHdr *headers, HTTPHdr *h2_headers)
 }
 
 Http2ErrorCode
-http2_encode_header_blocks(HTTPHdr *in, uint8_t *out, uint32_t out_len, uint32_t *len_written, HpackHandle &handle)
-{
+http2_encode_header_blocks(HTTPHdr *in, uint8_t *out, uint32_t out_len, uint32_t *len_written, HpackHandle &handle,
+                           int32_t maximum_table_size)
+{
+  // Limit the maximum table size to 64kB, which is the size advertised by major clients
+  maximum_table_size = min(maximum_table_size, 64 * 1024);
```
Comment (masaori335) [inline proxy/http2/HTTP2.cc]: It's better to make `64 * 1024` a constant variable.

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/517/

**Comment by atsci** [comment]
clang format *failed*! https://ci.trafficserver.apache.org/job/clang-format-github/269/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/283/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1964/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/265/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/394/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1856/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/527/

**Comment by masaori335** [comment]
I'm OK basically but atsci looks like still angry:( At least, clang-format should be passed.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/281/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/295/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/277/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1976/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/407/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1868/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/540/

**Comment by zwoop** [comment]
I've cherry-picked this to 7.1.x branch as well.
