### PR TITLE
Fix the implementation of Http2DependencyTree

### LINKED ISSUE #2268: wrong implementation on " stream dependent on a not exists parent"
see
https://github.com/http2/http2-spec/issues/764

### PR DESCRIPTION
**Pull request by scw00**
Fix #2268 

Changed log

 - Leaving `Node` alone and using `Http2DependencyTree` namespace instead

We defined the Node is shadow which the `node->t` is nullptr. 

We will create the shadow node if the parent node is not existed and the `exclusive` is true. And remove it if `children` and `queue` is empty.

The shadow nodes could become a real nodes if the real stream coming. And we set the `node->t` to the real stream.

### CODE REVIEW

File: proxy/http2/Http2DependencyTree.h [hunk 1]
```diff
@@ -37,80 +37,89 @@
...
 
-template <typename T> class Http2DependencyTree
+namespace Http2DependencyTree
+{
+class Node
 {
 public:
-  class Node
+  Node(void *t = nullptr)
+    : active(false),
```
Comment (SolidWallOfCode) [inline proxy/http2/Http2DependencyTree.h]: As long as this is being changed, it should use class initializers. E.g., instead of initializing `active` and `queued` in two different constructors, change the member definitions.
```
bool active=false;
bool queued=false;
```

Comment (maskit) [inline proxy/http2/Http2DependencyTree.h]: That's not on our coding style and the C++11 guideline is provided for REVIEW :)
https://cwiki.apache.org/confluence/display/TS/Coding+Style

Joking aside, we need a checklist, and notes. The change should be made with a separate commit. (Including it on the same PR is fine with me.)

File: proxy/http2/Http2DependencyTree.h [hunk 2]
```diff
@@ -155,23 +164,41 @@ Http2DependencyTree<T>::_find(Node *node, uint32_t id, uint32_t depth)
...
+  if (parent == nullptr) {
+    if (exclusive) {
+      parent = add(0, parent_id, weight, false, nullptr);
+    } else {
+      parent = _root;
+    }
+  }
+
+  Node *node = find(id);
+  if (node != NULL && node->is_shadow()) {
```
Comment (masaori335) [inline proxy/http2/Http2DependencyTree.h]: `nullptr` should be used.

Comment (masaori335) [inline proxy/http2/Http2DependencyTree.h]: It looks like `find(id)` never returns shadow node, right? If so, this condition never be true.
Do you want to call `find_shadow(id)` ?

Comment (scw00) [inline proxy/http2/Http2DependencyTree.h]: That's correct . I'll fix it!! Thanks

**Comment by scw00** [comment]
@masaori335 @maskit @SolidWallOfCode  Thanks for reviewing. Can you please review again ?

File: proxy/http2/Http2DependencyTree.h [hunk 3]
```diff
@@ -155,23 +155,43 @@ Http2DependencyTree<T>::_find(Node *node, uint32_t id, uint32_t depth)
...
+      parent = add(0, parent_id, weight, false, nullptr);
+    } else {
+      parent = _root;
+    }
+  }
+
+  Node *node = find_shadow(id);
+  if (node != nullptr && node->is_shadow()) {
+    node->t      = t;
+    node->point  = weight;
```
Comment (masaori335) [inline proxy/http2/Http2DependencyTree.h]: Could you use stream id as initial point like initializing Node in 6 lines below?

**Comment by scw00** [comment]
@masaori335 Updated!

File: proxy/http2/Http2DependencyTree.h [hunk 4]
```diff
@@ -155,23 +155,43 @@ Http2DependencyTree<T>::_find(Node *node, uint32_t id, uint32_t depth)
...
+Tree<T>::add(uint32_t parent_id, uint32_t id, uint32_t weight, bool exclusive, T t)
 {
   Node *parent = find(parent_id);
-  if (parent == NULL) {
-    parent = _root;
+  if (parent == nullptr) {
+    if (exclusive) {
+      parent = add(0, parent_id, weight, false, nullptr);
+    } else {
+      parent = _root;
```
Comment (masaori335) [inline proxy/http2/Http2DependencyTree.h]: Sorry, one more question. Why don't we need to create shadow node if exclusive flag is false?
In the original issue, the example is using `exclusive = true`, but it looks like RFC 7540 doesn't restrict the condition of exclusive flag.

> A dependency on a stream that is not currently in the tree -- such as a
stream in the "idle" state -- results in that stream being given a
default priority (Section 5.3.5).

File: proxy/http2/Http2DependencyTree.h [hunk 5]
```diff
@@ -155,23 +155,43 @@ Http2DependencyTree<T>::_find(Node *node, uint32_t id, uint32_t depth)
...
+template <typename T>
+Node *
+Tree<T>::add(uint32_t parent_id, uint32_t id, uint32_t weight, bool exclusive, T t)
 {
   Node *parent = find(parent_id);
-  if (parent == NULL) {
-    parent = _root;
+  if (parent == nullptr) {
+    if (exclusive) {
+      parent = add(0, parent_id, weight, false, nullptr);
```
Comment (masaori335) [inline proxy/http2/Http2DependencyTree.h]: This is creating shadow node, right? It looks like RFC 7540 says shadow node is given a default priority. Which means we should use `HTTP2_PRIORITY_DEFAULT_WEIGHT` as weight.
Please check [RFC7540 5.3.5. Default Priorities](http://httpwg.org/specs/rfc7540.html#pri-default).

**Comment by scw00** [comment]
That's correct ! I'll fix it.

**Comment by zwoop** [comment]
This wouldn't fix / address any of the ASAN issues I'm seeing does it?

**Comment by zwoop** [comment]
Status on this? It's having merge conflicts now :-). Also, this is a candidate for 7.x ? If so, 7.1.1 or 7.1.2 ? Or 7.2.0 ?

**Comment by masaori335** [comment]
This needs some changes. And I think this doesn't block release of 7.1.1, so this is a candidate for 7.1.2 or 7.2.0.

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
[approve ci Linux]

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
[approve ci Linux]

**Comment by bryancall** [comment]
@scw00 There is a conflict on the PR, can you please resolve it so we can merge it in.

**Comment by scw00** [comment]
@bryancall Fixed the conflict!

**Comment by scw00** [comment]
@masaori335 Can you please approve again! I'll merge it.

**Comment by zwoop** [comment]
Question: Do we want this for 7.1.2, or wait for either 7.2.0 or 8.0.0, whichever comes first ? This does not cherry-pick cleanly to 7.1.x branch, so if we need it there, we will need a new PR.

**Comment by masaori335** [comment]
It'd be great if 7.1.2 has this. I'll create a PR.
