### PR TITLE
Make code buildable with BoringSSL

### LINKED ISSUE #5775: Cannot build with BoringSSL again
Build with BoringSSL fails because `SSL_get_shared_curve` is not available. The code was added by #5724.

### PR DESCRIPTION
**Pull request by maskit**
Checked with the latest BoringSSL (f7b830d8df9f5578c748aa0283d44c59ea7eeb25).

This fixes #5775. The logging tag which was added by #5724 to log a curve name works at minimum, but not sure about the plugins.

### CODE REVIEW

File: example/plugins/c-api/client_context_dump/client_context_dump.cc [hunk 1]
```diff
@@ -116,7 +116,7 @@ dump_context(const char *ca_path, const char *ck_path)
 
         // Serial number
         int64_t sn = 0;
-#if OPENSSL_VERSION_NUMBER >= 0x010100000
+#if !defined(OPENSSL_IS_BORINGSSL) && OPENSSL_VERSION_NUMBER >= 0x010100000
```
Comment (bryancall) [inline example/plugins/c-api/client_context_dump/client_context_dump.cc]: Just a nit, but your conditional in cert_reporting_tool.cc has braces around OPENSSL_VERSION_NUMBER comparison and this one doesn't.

Comment (maskit) [reply example/plugins/c-api/client_context_dump/client_context_dump.cc]: Added parens.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
