### PR TITLE
Fix HTTP/3 crash in HQTransaction::_signal_event

### LINKED ISSUE #12112: HttpSM.cc:2627: failed assertion `default_handler != (HttpSMHandler) nullptr`
I noticed the following crash (from traffic.out, passed through c++filt) on the docs server:

```
Fatal: /home/bneradt/src/trafficserver_10/src/proxy/http/HttpSM.cc:2627: failed assertion `default_handler != (HttpSMHandler) nullptr`
[Mar 11 04:02:19.504] traffic_crashlo NOTE: crashlog started, target=3024710, debug=false syslog=true, uid=0 euid=0
[Mar 11 04:02:19.509] traffic_crashlo NOTE: logging to 0x615000003c80
[Mar 11 04:02:22.652] traffic_crashlo ERROR: wrote crash log to /opt/ats/var/log/trafficserver/crash-2025-03-11-040219.log
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE: 
/opt/ats/bin/traffic_server(signal_crash_handler(int, siginfo_t*, void*)+0x1c)[0x5620c0e30d7b]
/opt/ats/bin/traffic_server(crash_logger_invoke(int, siginfo_t*, void*)+0x180)[0x5620c0d911d6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f77a060f420]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f77a044c00b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f77a042b859]
/opt/ats/bin/traffic_server(ink_warning(char const*, ...)+0x0)[0x5620c0e06b12]
/opt/ats/bin/traffic_server(+0xbca420)[0x5620c0e01420]
/opt/ats/bin/traffic_server(HttpSM::main_handler(int, void*)+0x5e7)[0x5620c0f01cb3]
/opt/ats/bin/traffic_server(Continuation::handleEvent(int, void*)+0x1e3)[0x5620c0d9f6d3]
/opt/ats/bin/traffic_server(HQTransaction::_signal_event(int, Event*)+0x1ea)[0x5620c17966e2]
/opt/ats/bin/traffic_server(Http3Transaction::state_stream_open(int, Event*)+0x1200)[0x5620c1799364]
/opt/ats/bin/traffic_server(Continuation::handleEvent(int, void*)+0x1e3)[0x5620c0d9f6d3]
/opt/ats/bin/traffic_server(HQSession::main_event_handler(int, void*)+0x24b)[0x5620c17904b1]
/opt/ats/bin/traffic_server(Continuation::handleEvent(int, void*)+0x1e3)[0x5620c0d9f6d3]
/opt/ats/bin/traffic_server(QUICNetVConnection::_propagate_event(int)+0x286)[0x5620c16157c4]
/opt/ats/bin/traffic_server(QUICNetVConnection::state_established(int, Event*)+0x1ff)[0x5620c1614b41]
/opt/ats/bin/traffic_server(Continuation::handleEvent(int, void*)+0x1e3)[0x5620c0d9f6d3]
/opt/ats/bin/traffic_server(EThread::process_event(Event*, int)+0x347)[0x5620c1716791]
/opt/ats/bin/traffic_server(EThread::process_queue(Queue<Event, Event::Link_link>*, int*, int*)+0x1d5)[0x5620c1716ce5]
/opt/ats/bin/traffic_server(EThread::execute_regular()+0x3d6)[0x5620c171727c]
/opt/ats/bin/traffic_server(EThread::execute()+0x30c)[0x5620c1717d28]
/opt/ats/bin/traffic_server(+0x14dd9c9)[0x5620c17149c9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7f77a0603609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f77a0528353]
```

It's a rare crash, only happening once in the last couple months.

In case it's helpful, here's the bt from crash logger:

```
Thread 3024729, [ET_NET 0]:
0    0x00007f77a15b4510 __interceptor_waitpid.part.0 + 0x40
1    0x00005620c0d91180 crash_logger_invoke(int, siginfo_t*, void*) + 0x12a
2    0x00007f77a060f420 funlockfile + 0x60
3    0x00007f77a044c00b gsignal + 0xcb
4    0x00007f77a042b859 abort + 0x12b
5    0x00005620c0e06b12 ink_abort(char const*, ...) + 0x126
6    0x00005620c0e01420 _ink_assert(char const*, char const*, int) + 0x3b
7    0x00005620c0f01cb3 HttpSM::main_handler(int, void*) + 0x5e7
8    0x00005620c0d9f6d3 Continuation::handleEvent(int, void*) + 0x1e3
9    0x00005620c17966e2 HQTransaction::_signal_event(int, Event*) + 0x1ea
10   0x00005620c1799364 Http3Transaction::state_stream_open(int, Event*) + 0x1200
11   0x00005620c0d9f6d3 Continuation::handleEvent(int, void*) + 0x1e3
12   0x00005620c17904b1 HQSession::main_event_handler(int, void*) + 0x24b
13   0x00005620c0d9f6d3 Continuation::handleEvent(int, void*) + 0x1e3
14   0x00005620c16157c4 QUICNetVConnection::_propagate_event(int) + 0x286
15   0x00005620c1614b41 QUICNetVConnection::state_established(int, Event*) + 0x1ff
16   0x00005620c0d9f6d3 Continuation::handleEvent(int, void*) + 0x1e3
17   0x00005620c1716791 EThread::process_event(Event*, int) + 0x347
18   0x00005620c1716ce5 EThread::process_queue(Queue<Event, Event::Link_link>*, int*, int*) + 0x1d5
19   0x00005620c171727c EThread::execute_regular() + 0x3d6
20   0x00005620c1717d28 EThread::execute() + 0x30c
21   0x00005620c17149c9 spawn_thread_internal(void*) + 0x14e
22   0x00007f77a0603609 start_thread + 0xd9
23   0x00007f77a0528353 clone + 0x43
```

The docs server was running the ATS 10 version built from tag `10.0.3-rc1`.

### PR DESCRIPTION
**Pull request by bneradt**
I'm running this is docs now and I have no longer seen this rather frequent
crash.

---

This fixes a crash where the assertion at HttpSM.cc:2765 fails:

  ink_assert(default_handler != (HttpSMHandler) nullptr)

The crash is triggered when VC_EVENT_EOS, VC_EVENT_ERROR, or a
timeout propagates from the QUIC stream up to
HQTransaction::state_stream_open, which calls _signal_event. The
previous implementation forwarded the triggering Event* as the data
argument to HttpSM::handleEvent. HttpSM::main_handler, however, casts
that data to VIO* and uses it to look up the vc_table entry. Because
an Event* never matches any registered VIO, find_entry returns null
and main_handler falls through to default_handler. When the SM is in
early setup or has already been torn down (kill_this clears
default_handler), default_handler is null and the assertion fires.

This patch passes the appropriate VIO pointer to each handleEvent
call, matching the convention used by _signal_read_event,
_signal_write_event, and the HTTP/2 Http2Stream equivalents. The
original dual-VIO dispatch is preserved so tunnel consumers bound to
the write side still receive connection-level events.

Fixes: #12112

### CODE REVIEW

File: src/proxy/http3/Http3Transaction.cc [hunk 1]
```diff
@@ -353,15 +353,17 @@ HQTransaction::_close_write_complete_event(Event *e)
...
+  // can locate the vc_table entry.
   if (this->_write_vio.cont) {
     SCOPED_MUTEX_LOCK(lock, this->_write_vio.mutex, this_ethread());
-    this->_write_vio.cont->handleEvent(event, edata);
+    this->_write_vio.cont->handleEvent(event, &this->_write_vio);
   }
   if (this->_read_vio.cont && this->_read_vio.cont != this->_write_vio.cont) {
     SCOPED_MUTEX_LOCK(lock, this->_read_vio.mutex, this_ethread());
-    this->_read_vio.cont->handleEvent(event, edata);
+    this->_read_vio.cont->handleEvent(event, &this->_read_vio);
```
Comment (bneradt) [inline src/proxy/http3/Http3Transaction.cc:366]: If you look at [src/proxy/http2/Http2Stream.cc](https://github.com/apache/trafficserver/blob/12fdb0730899ce95d19f4ded25c408390b9faf9d/src/proxy/http2/Http2Stream.cc), everywhere where handleEvent is called, we pass a vio, not edata. This seems to confirm what Claude did here. And, as mentioned in the description, I no longer see these crashes anymore on docs with this change.

**Review by maskit — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to 10.2.x
