### PR TITLE
Cancel closing if Http2SendDataFrameResult is NO_WINDOW

### LINKED ISSUE #2795: HTTP/2 AuTest Failed Intermittently
Sometime (not always) "Test Case 4: Multiple request" of HTTP/2 AuTest failed.
```
   Run: 3-general: Failed
     Test : Checking that True == _isRunningAfter - Passed
        Reason: Returned Value: True == _isRunningAfter
     Starting TestRun 3-general : No Issues found - Passed
        Reason: Started!
     Process: Default: Failed
       Test : Checking that ReturnCode == 0 - Passed
          Reason: Returned Value: 0 == 0
       Stream stdout : Checking that StdOutFile matches gold/replay.gold - Failed
          Reason: File differences
           Gold File : /Users/masaori/src/github.com/apache/trafficserver/tests/gold_tests/h2/gold/replay.gold
           Data File : /tmp/autest_sandbox/http2/_tmp_http2_3-general_Default/stream.stdout.txt
             Dropped 0 sessions for being malformed. Number of correct sessions 1
             range(0, 4)
             processProcess-1 has exited
             processProcess-2 has exited
             processProcess-3 has exited
             False
             PASS
             PASS
           - PASS
           + processProcess-4 has exited
             OK enough, it is time to exit, running time in seconds 0.034689903259277344
```

### PR DESCRIPTION
**Pull request by masaori335**
Fix #2795.

This is a candidate for 7.1.2 backport.

### CODE REVIEW

File: proxy/http2/Http2Stream.cc [hunk 1]
```diff
@@ -327,7 +327,12 @@ Http2Stream::do_io_close(int /* flags */)
     if (parent && this->is_client_state_writeable()) {
       // Make sure any trailing end of stream frames are sent
       // Wee will be removed at send_data_frames or closing connection phase
-      static_cast<Http2ClientSession *>(parent)->connection_state.send_data_frames(this);
+      Http2SendDataFrameResult result = static_cast<Http2ClientSession *>(parent)->connection_state.send_data_frames(this);
+      if (result == Http2SendDataFrameResult::NO_WINDOW) {
+        Http2StreamDebug("cancel closing");
+        closed = false;
+        return;
```
Comment (maskit) [inline proxy/http2/Http2Stream.cc]: When will `do_io_close` be called again in this case? On receiving WINDOW_UPDATE?

File: proxy/http2/Http2Stream.cc [hunk 2]
```diff
@@ -327,7 +327,12 @@ Http2Stream::do_io_close(int /* flags */)
     if (parent && this->is_client_state_writeable()) {
       // Make sure any trailing end of stream frames are sent
       // Wee will be removed at send_data_frames or closing connection phase
-      static_cast<Http2ClientSession *>(parent)->connection_state.send_data_frames(this);
+      Http2SendDataFrameResult result = static_cast<Http2ClientSession *>(parent)->connection_state.send_data_frames(this);
+      if (result == Http2SendDataFrameResult::NO_WINDOW) {
+        Http2StreamDebug("cancel closing");
+        closed = false;
```
Comment (maskit) [inline proxy/http2/Http2Stream.cc]: Can we set this flag to `true` right before the `clear_timers()` below?

File: proxy/http2/Http2Stream.cc (hunk 1 above)
Comment (shinrich) [reply proxy/http2/Http2Stream.cc]: Yes, the window update should cause the data to be sent again.  If the end of the data has been transmitted into the stream before the do_io_close, eventually the end frame will be sent, and the stream shutdown will be started again.  If the do_io_close was called in response to an error case, I would be worried that we would have to wait for a timeout before the stream finishes.

**Comment by zwoop** [comment]
Should we land this?

**Comment by zwoop** [comment]
Running on Docs now too.

**Comment by shinrich** [comment]
I'm still staring at this.   Trying to understand what changes to make this start failing.

File: proxy/http2/Http2Stream.cc (hunk 2 above)
Comment (maskit) [inline proxy/http2/Http2Stream.cc]: `super::release(nullptr)` is already called at the beginning of `do_io_close`. Wouldn't it be a problem?

Comment (masaori335) [reply proxy/http2/Http2Stream.cc]: It looks like do nothing now. But it could be problem in the future. I'll move this call.
https://github.com/apache/trafficserver/blob/4d4283ea26f709fc9a7efea3283f1acc401bab0a/proxy/ProxyClientTransaction.cc#L71
https://github.com/apache/trafficserver/blob/4d4283ea26f709fc9a7efea3283f1acc401bab0a/proxy/http2/Http2ClientSession.h#L232-L235

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
@shinrich It looks like this bug has existed for long time. And traffic_replay couldn't detect this because it checks only response headers if I understand correctly.
Recently, bc3ecafb9f67243a152f00affe6af4dff752d7a0 started sending RST_STREAM in this case and traffic_replay detected that.

**Comment by shinrich** [comment]
Hmm.  Still odd.  We should extend traffic_replay to actually check the body length.  The h2bigfile test does test the actual body length.  It was put in to check for a regression in that area (terminating too soon when data not sent due to window size issues).  But that test is only doing one request for the H2 session.

**Comment by masaori335** [comment]
@shinrich This sessionlog.json for traffic_replay makes the failure rate higher, but it's still intermittent. https://paste.apache.org/9i1G

I agree this is dicey. But do_io_close is called from HttpSM regardless state of Http2Stream :(

**Comment by masaori335** [comment]
( The traffic_replay issue is reported as #2817 )

**Comment by zwoop** [comment]
Cherry-picked to 7.1.2.

**Comment by zwoop** [comment]
I'll have to spend a little more time on this, but I think that this causes us to leak active connections. Over time, we'll run out of active connections with this PR it seems, causing us to throttle.

**Comment by maskit** [comment]
We should have looked into it more carefully. I found these lines, I don't think the lines are not the cause of connections leak though. Probably nobody expects that `do_io_close()` can be cancelled.
https://github.com/apache/trafficserver/blob/master/proxy/http2/Http2Stream.cc#L358-L361

**Comment by zwoop** [comment]
I've reverted this from 7.1.x for now, since it causes H2 connection leaks.
