### PR TITLE
s3_auth does not retry after a file read error

### LINKED ISSUE #11831: s3_auth does not retry after a file read error
If s3_auth attempts to load its configuration from file and fails due to a file system error, it will not retry on its own.  This can cause credentials to expire without being renewed.

### PR DESCRIPTION
**Pull request by jasmine-nahrain**
Currently, if a config file is invalid or cannot be opened/read, ATS does not retry loading the config. As a result, if there is something wrong, ATS will not retry which can lead to 400 errors until there is manual intervention.

This adds an exponential retry to loading and validating the config. 

This fixes #11831

### CODE REVIEW

File: plugins/origin_server_auth/origin_server_auth.cc [hunk 1]
```diff
@@ -1087,9 +1100,12 @@ config_reloader(TSCont cont, TSEvent /* event ATS_UNUSED */, void *edata)
   S3Config *file_config = gConfCache.get(s3->conf_fname());
 
   if (!file_config || !file_config->valid()) {
-    TSError("[%s] invalid configuration. Check mandatory fields.", PLUGIN_NAME);
+    TSError("[%s] invalid configuration. Check mandatory fields. Scheduling reload", PLUGIN_NAME);
+    long delay = pow(s3->incr_invalid_file_count(), 2);
```
Comment (masaori335) [inline plugins/origin_server_auth/origin_server_auth.cc:1105]: Do you mean power of 2?  Please use bitwise left shift `1 << s3->incr_invalid_file_count()`.

**Review by bneradt — APPROVED** [review]

**Comment by ezelkow1** [comment]
Do we still want this for 9.2?

**Comment by jasmine-nahrain** [comment]
No
