### PR TITLE
Change remap loading to be fatal during startup.

### LINKED ISSUE #8785: 9.2.x: invalid remap.config files are no longer FATAL
While testing 9.2.x, I accidentally created an invalid remap.config file. In previous releases, ATS would fail to start if it loaded an invalid remap.config file and it would emit a FATAL log message. In 9.2.0 (not released yet), this is no longer the case: ATS starts, albeit with ERROR messages.

This change looks intentional per the following PR: #7782

However we might want to reconsider this because this is a pretty significant change in behavior that can lead to confusing 404 responses for the user. Consider the following possible scenario:

1. An admin creates a problematic remap.config entry near the end of the file, maybe 95% down.
2. They restart ATS. In 9.1, ATS would refuse to come up with a FATAL message. In 9.2, it now emits an ERROR but does start with the previous remap entries active in its running state.
3. Since the majority of the remap.config entries were parsed, their smoke testing shows that the remap.config file seems to work. Remapping works fine in general, and unless they test entries at or after their corrupted remap.config entry, remapping will seem to work.
4. This runs in prod for a while and the diags.log file is rotated.
5. The admin gets reports about unexpected 404 errors due to the few entries near the bottom of the remap.config file.

In this situation, he does not see diags.log errors anymore because they only happened after ATS restart. The corruption in the remap.config may not be obvious. In fact, particular entries may be fine with their only problem being that they come after the corrupted entry, which may be many lines before that for which the current 404 responses correspond. Thus for large remap.config files (ours are thousands of lines long), a corrupted entry may be almost impossible to detect visually.

Perhaps it's preferable for reloads to be more lenient, while keeping initial remap.config loading strict?

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This also enables a missing "remap.config" to be treated as an empty file (that is, it "parses" successfully and yields no remap rules).

Due to feedback, this now adds a configuration variable, "proxy.config.url_remap.min_rules_required" to control how many rules are need in "remap.config" to be considered a valid configuration. With this a deployment can easily tune whether empty/missing file is acceptable. The PR has been updated with documentation and tests for this. Note the value is dynamic and it is therefore possible to have different behavior on startup vs. runtime (e.g. allow empty on start but not on reload).

Closes #8785

### CODE REVIEW

**Review by bneradt — APPROVED** [review]

**Comment by bneradt** [comment]
Thanks for working on this @SolidWallOfCode.

I think we'll want to mark this for the 9.2.x project as well since the patch that introduced the issue went into 9.2.x.

File: proxy/http/remap/RemapConfig.cc [hunk 1]
```diff
@@ -944,6 +944,9 @@ remap_parse_config_bti(const char *path, BUILD_TABLE_INFO *bti)
 
   std::error_code ec;
   std::string content{ts::file::load(ts::file::path{path}, ec)};
+  if (ec.value() == ENOENT) { // a missing file is ok - treat as empty, no rules.
```
Comment (randall) [inline proxy/http/remap/RemapConfig.cc:947]: Maybe I haven't had enough coffee today, but how is a missing file ok? I know we'd want that to be a failure for our systems.

**Review by randall — CHANGES_REQUESTED** [review]
Just want some clarification before this is merged.

**Comment by bneradt** [comment]
[approve ci fedora]

**Comment by ezelkow1** [comment]
Does this still allow a remap to be partially loaded when it's bad? IMHO that's still a very bad issue since it allows problems to crop up that are even worse than just not reloading the file, you could end up with all_services-1 not being able to serve

File: proxy/http/remap/RemapConfig.cc (hunk 1 above)
Comment (SolidWallOfCode) [reply proxy/http/remap/RemapConfig.cc:947]: As a general policy for ATS we want to not require the existence of configuration files. If an empty file is acceptable, it shouldn't be required to actually put one there.

**Comment by SolidWallOfCode** [comment]
No. The partial loading still happens during startup, but ATS is then immediately shut down so it's irrelevant. Reloads continue to be atomic (all or nothing of the new configuration).

**Comment by bneradt** [comment]
> As such, my strong preference is that we back out this train of PRs from 9.2.x, and roll forward with 10.0.x

In that case, we should revert #7782 from 9.2.x and not cherry-pick this PR to 9.2.x. I'll create a PR to revert #7782 from 9.2.x.

**Comment by zwoop** [comment]
I think @SolidWallOfCode has a strong preference to not revert.

File: proxy/http/remap/RemapConfig.cc (hunk 1 above)
Comment (mlibbey) [reply proxy/http/remap/RemapConfig.cc:947]: We have a specific setting to not force having a remap.config -- proxy.config.url_remap.remap_required https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-url-remap-remap-required, which has existed since the first commit. I'd expect a missing file to need that setting set to 0.

Comment (SolidWallOfCode) [reply proxy/http/remap/RemapConfig.cc:947]: No, that setting means a remap rule is not required to forward the transaction. It has nothing to do with whether there is an actual "remap.config" file.

**Comment by SolidWallOfCode** [comment]
I went back and checked. Prior to #7782 a missing "remap.config" was allowed. This is a reversion to previous behavior.

I have checked this in four cases to verify the operation is what is requested.

1. Valid, empty, missing "remap.config" at start up - successful start.
2. "remap.config" containing an error at start up - emergency shutdown (no restart).
3.  Valid, empty, missing "remap.config" for reload - remap rules are updated.
4. "remap.config" containing an error for reload - remap rules are not updated.

This makes "remap.config" loading atomic - all of the file, or none of it.

File: proxy/http/remap/RemapConfig.cc (hunk 1 above)
Comment (ywkaras) [reply proxy/http/remap/RemapConfig.cc:947]: > We have a specific setting to not force having a remap.config -- proxy.config.url_remap.remap_required https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-url-remap-remap-required, which has existed since the first commit. I'd expect a missing file to need that setting set to 0.

This also seems correct to me.  Do we at least want a warning in diags.log if remap.config is empty?  Do we know of ATS users who don't do any remapping?

**Comment by bryancall** [comment]
Since ATS prior to #7782 has the features you want, can't we just revert #7782?  If not what is the difference in behavior now vs pre-#7782?

**Comment by SolidWallOfCode** [comment]
This change unifies start up and reload handling of "remap.config". It also changes startup failure to `Emergency` from `Fatal` to avoid a restart loop.  I've also tested this version and verified it behaves as requested.

However, due to some pushback, I plan to add a configuration variable to enable requiring a minimum number of rules in the "remap.config" to be valid. The default, at least for 9.2, will be 1. This means an empty or missing file won't replace a valid file. That can be changed by adjusting the configuration value. LinkedIn and Apple. I pondered a configuration for requiring a file but decided that was too indirect - a file with just comments is really an empty file. Valid rules are the correct metric for determining the "emptiness" of a file.

**Comment by bryancall** [comment]
@bneradt is going to review this

File: doc/admin-guide/files/records.config.en.rst [hunk 2]
```diff
@@ -3477,6 +3477,14 @@ URL Remap Rules
    Set this variable to ``1`` if you want to retain the client host
    header in a request during remapping.
 
+.. ts::cv CONFIG proxy.config.url_remap.min_rules_required INT 1
```
Comment (bneradt) [inline doc/admin-guide/files/records.config.en.rst:3480]: `ts::cv` -> `ts:cv`  (one colon)

**Review by bneradt — CHANGES_REQUESTED** [review]

File: doc/admin-guide/files/records.config.en.rst (hunk 2 above)
Comment (SolidWallOfCode) [reply doc/admin-guide/files/records.config.en.rst:3480]: Not quite - should be `ts:cv::`

Comment (bneradt) [reply doc/admin-guide/files/records.config.en.rst:3480]: I think this will address the doc build rule:
https://ci.trafficserver.apache.org/job/Github_Builds/job/docs/905/console

File: doc/admin-guide/files/records.config.en.rst [hunk 3]
```diff
@@ -3477,6 +3477,14 @@ URL Remap Rules
    Set this variable to ``1`` if you want to retain the client host
    header in a request during remapping.
 
+.. ts:cv:: CONFIG proxy.config.url_remap.min_rules_required INT 1
```
Comment (bneradt) [inline doc/admin-guide/files/records.config.en.rst:3480]: I believe we want to use `0` here since that's the default.

File: doc/admin-guide/files/records.config.en.rst [hunk 4]
```diff
@@ -3477,6 +3477,14 @@ URL Remap Rules
...
+   :reloadable:
+
+   The minimum number of rules :file:"remap.config" must have to be considered valid. An otherwise
+   valid configuration with fewer than this many rules is considered to be invalid. To allow an empty
+   or missing file value must be zero. This is dynamic to enable different requirements for
```
Comment (bneradt) [inline doc/admin-guide/files/records.config.en.rst:3485]: > To allow an empty or missing file value must be zero.

I suggest:

> A value of zero, the default, allows for either a :file:"remap.config" that has no rules in it or a non-existing :file:"remap.config" file.

File: tests/gold_tests/remap/remap_reload.test.py [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+
+nameserver = Test.MakeDNServer("dns", default='127.0.0.1')
+tm.Disk.records_config.update({
+    'proxy.config.dns.nameservers': f"127.0.0.1:{nameserver.Variables.Port}", 'proxy.config.dns.resolv_conf': 'NULL'
+})
+
+# tm.Disk.records_config.update({
+#    'proxy.config.diags.debug.enabled': 1,
+#    'proxy.config.diags.debug.tags': 'http|dns|hostdb',
+# })
```
Comment (bneradt) [inline tests/gold_tests/remap/remap_reload.test.py:48]: Probably remove this commented out code?

**Review by bneradt — CHANGES_REQUESTED** [review]
Looks good. Just a few minor suggestions.

**Review by zwoop — DISMISSED** [review]
Thanks Alan, appreciate you humoring the senile old geyser.

File: tests/gold_tests/remap/remap_reload.test.py (hunk 5 above)
Comment (SolidWallOfCode) [reply tests/gold_tests/remap/remap_reload.test.py:48]: I debated that - it's handy if the test goes wrong, but I suppose it's easy enough to clone when needed.

Comment (bneradt) [reply tests/gold_tests/remap/remap_reload.test.py:48]: Oh, I see. I'm fine leaving it in. Please just add a comment saying something like: `# Uncomment for diagnostic logging.`

**Review by randall — DISMISSED** [review]
Thanks ! This is great!

**Review by bneradt — APPROVED** [review]
