### PR TITLE
Make code compilable with BoringSSL

### LINKED ISSUE #5397: Cannot build with BoringSSL
I got these errors below with the latest BoringSSL (1b878e7cc69f60407457024a212750c52bcc9ae5):
```
Making all in net
  CXX      SSLUtils.o
SSLUtils.cc:922:15: error: use of undeclared identifier 'ENGINE_get_default_RSA'
  ENGINE *e = ENGINE_get_default_RSA();
              ^
SSLUtils.cc:925:38: error: use of undeclared identifier 'ENGINE_load_private_key'
    if (!SSL_CTX_use_PrivateKey(ctx, ENGINE_load_private_key(e, argkey, nullptr, nullptr))) {
                                     ^
2 errors generated.
```

This is different from OCSP (#3748).

### PR DESCRIPTION
**Pull request by maskit**
This makes ATS compilable with BoringSSL, however, I have no idea what features I disabled. As far as I can see, it fails appropriately.

This closes #5397

### CODE REVIEW

File: plugins/experimental/access_control/utils.cc [hunk 1]
```diff
@@ -27,6 +27,7 @@
 #include <openssl/bio.h>    /* BIO I/O abstraction */
 #include <openssl/buffer.h> /* buf_mem_st */
 #include <openssl/err.h>    /* ERR_get_error() and ERR_error_string_n() */
+#include <openssl/crypto.h>
```
Comment (maskit) [inline plugins/experimental/access_control/utils.cc]: This is for `CRYPTO_memcmp`.

File: plugins/experimental/access_control/utils.cc [hunk 2]
```diff
@@ -253,7 +254,11 @@ cryptoMessageDigestGet(const char *digestType, const char *data, size_t dataLen,
   if (!(ctx = EVP_MD_CTX_create())) {
     AccessControlError("failed to create EVP message digest context: %s", cryptoErrStr(buffer, sizeof(buffer)));
   } else {
+#ifndef OPENSSL_IS_BORINGSSL
```
Comment (maskit) [inline plugins/experimental/access_control/utils.cc]: According to BoringSSL's documentation:
> EVP_PKEY_HMAC is removed. Use the HMAC_* functions in hmac.h instead. This is compatible with OpenSSL.

File: iocore/net/SSLSessionTicket.h [hunk 3]
```diff
@@ -25,6 +25,7 @@
 
 #include <openssl/safestack.h>
 #include <openssl/tls1.h>
+#include <openssl/ssl.h>
```
Comment (maskit) [inline iocore/net/SSLSessionTicket.h]: `SSL_CTX_set_tlsext_ticket_key_cb`, which is checked on line 31, is defined in "ssl.h". Without including the header file here, the check can fail on some files.

File: iocore/net/SSLUtils.cc [hunk 4]
```diff
@@ -928,12 +928,17 @@ SSLMultiCertConfigLoader::default_server_ssl_ctx()
...
+#ifndef OPENSSL_IS_BORINGSSL
   ENGINE *e = ENGINE_get_default_RSA();
   if (e != nullptr) {
     const char *argkey = (keyPath == nullptr || keyPath[0] == '\0') ? completeServerCertPath.c_str() : keyPath;
     if (!SSL_CTX_use_PrivateKey(ctx, ENGINE_load_private_key(e, argkey, nullptr, nullptr))) {
       SSLError("failed to load server private key from engine");
     }
+#else
+  ENGINE *e = nullptr;
+  if (false) {
```
Comment (maskit) [inline iocore/net/SSLUtils.cc]: Just setting nullptr is not enough because `ENGINE_load_private_key` is also not available.

**Review by bryancall — APPROVED** [review]

**Comment by maskit** [comment]
@shinrich If I understand #3902 correctly things should work without the block I disabled, but it would be great if you could file an issue for the feature, like #3748, if necessary.

**Comment by bryancall** [comment]
I cherry picked this into the 8.0.6 release
