### PR TITLE
Separate mutex of Http2ClientSession and Http2Stream

### LINKED ISSUE #3100: Parent Selection with HTTP/2 has performance issue
# Summary
We found weird performance issue with parent.config. Using h2load, requests with HTTP/1.1 seems ok, but some requests (2 ~ 9%) with HTTP/2 is failed.

# Conditions
- Origin server is running on 127.0.0.1:8001. 
- ATS has below configs
  - HEAD of 7.1.x branch (eeae4118315283dc188249a4f3c7826836a4b4cb)
  - records.config and ssl_multicert.config has some changes to enable HTTP/2 on 4443
  -  parant.config
  ```
  dest_domain=. parent="localhost:8001" round_robin=consistent_hash
  ```
  - remap.config
  ```
  map / http://127.0.0.1:8001/
  ```
- 100KB content is cached

# Tests
## HTTP/2
```
$ h2load -n 10000 -m 100 -c 2 https://127.0.0.1:4443/100k
starting benchmark...
spawning thread #0: 2 total client(s). 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 5.87s, 1661.31 req/s, 162.37MB/s
requests: 10000 total, 10000 started, 10000 done, 9744 succeeded, 256 failed, 256 errored, 0 timeout
status codes: 9744 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 952.34MB (998598258) total, 105.15KB (107676) headers (space savings 96.39%), 951.56MB (997785600) data
                     min         max         mean         sd        +/- sd
time for request:      954us       1.90s    112.14ms    160.98ms    96.13%
time for connect:     5.43ms      8.64ms      7.03ms      2.27ms   100.00%
time to 1st byte:   440.40ms    444.99ms    442.69ms      3.24ms   100.00%
req/s           :     808.84      966.39      887.62      111.40   100.00%
```

## HTTP/1.1
```
$ h2load --h1 -n 10000 -m 100 -c 2 https://127.0.0.1:4443/100k
starting benchmark...
spawning thread #0: 2 total client(s). 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: http/1.1
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 2.90s, 3453.07 req/s, 338.46MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 980.18MB (1027790000) total, 3.01MB (3160000) headers (space savings 0.00%), 976.56MB (1024000000) data
                     min         max         mean         sd        +/- sd
time for request:      622us    366.62ms     51.13ms     59.50ms    88.65%
time for connect:     3.47ms      3.52ms      3.50ms        39us   100.00%
time to 1st byte:     4.04ms      4.97ms      4.50ms       660us   100.00%
req/s           :    1726.73     2223.60     1975.17      351.34   100.00%
```

### PR DESCRIPTION
**Pull request by masaori335**
When parent selection feature is enabled, TS starts dns reverse lookup on every transaction. With HTTP/2, `HostDBProcessor::getby()` is called simultaneously and lock contention starts. This serialize the transactions of HTTP/2. 

https://github.com/apache/trafficserver/blob/e4aa18e3337929bb1c9dc4272f369c86a1325c61/iocore/hostdb/HostDB.cc#L652

### Before
screen shot 2018-02-20 at 11 10 28

### After
screen shot 2018-02-20 at 15 35 51

Also debug logs of hostdb says "getby" got immediate answer in many cases.

### Before
```
10000 <HostDB.cc:485 (reply_to_cont)> (hostdb) hostname = localhost
7786 <HostDB.cc:664 (getby)> (hostdb) immediate answer for 127.0.0.1
2214 <HostDB.cc:675 (getby)> (hostdb) delaying force 0 answer for 127.0.0.1
```

### After
```
10000 <HostDB.cc:485 (reply_to_cont)> (hostdb) hostname = localhost
9913 <HostDB.cc:664 (getby)> (hostdb) immediate answer for 127.0.0.1
87 <HostDB.cc:675 (getby)> (hostdb) delaying force 0 answer for 127.0.0.1
```

----
- Fix #3100 b)
- ~~Backport 7.1.3 candidate~~ 7.2.0 candidate

### CODE REVIEW

**Comment by maskit** [comment]
I haven't looked into the detail but my only concern is HPACK. We need to acquire a lock for session before accessing HPACK tables.

**Comment by masaori335** [comment]
As for receiving frame, HPACK is covered by mutex of `Http2ConnectionState`.
As for sending frame, `send_headers_frame()` is called from `Http2Stream` and it looks not covered by mutex of `Http2ClientSession` or `Http2ConnectionState`. I'll take a look more.

Actually, I also worry about metrics and connection level flow control.

**Comment by masaori335** [comment]
@zizhong Could you please take a look? We need more eye balls.

**Comment by zizhong** [comment]
@masaori335 sure. Will do.

File: proxy/http2/Http2Stream.cc [hunk 1]
```diff
@@ -671,10 +675,12 @@ Http2Stream::send_response_body(bool call_update)
   Http2ClientSession *parent = static_cast<Http2ClientSession *>(this->get_parent());
 
   if (Http2::stream_priority_enabled) {
+    SCOPED_MUTEX_LOCK(lock, parent->connection_state.mutex, this_ethread());
```
Comment (zizhong) [inline proxy/http2/Http2Stream.cc]: is this one necessary?

**Comment by zizhong** [comment]
Overall looks good to me that all the write operations get the right locks.
Didn't check the risk of deadlock. @masaori335 do we need to worry about it?

**Comment by zwoop** [comment]
I'm not wildly familiar with this code, but it feels like we should free this stream mutex at some point? Or is there C++ magic happening here somewhere ?

**Comment by masaori335** [comment]
@zwoop It's refcount object, so when `ProxyClientTransaction::destroy()` is called, it should be freed. But I'll check again.

**Comment by masaori335** [comment]
@zizhong Thanks. Yes, it could be. I'm checking it with TSan and it reports some potential deadlocks. I'm looking them. https://paste.apache.org/Mpln

**Comment by masaori335** [comment]
@zwoop What I said was little bit wrong. When `ProxyClientTransaction::destroy()` is called from `Http2Stream::destroy()`, the `mutex.m_ptr->m_refcount` is not `0`.
But when `mutex.m_ptr->m_refcount` is `0`, it is freed finally.

https://paste.apache.org/gUij

File: proxy/http2/Http2Stream.cc (hunk 1 above)
Comment (masaori335) [reply proxy/http2/Http2Stream.cc]: This is not necessary, because `Http2ConnectionState::schedule_stream()` acquire mutex by itself. But I add this for consistency with else block (calling `Http2ConnectionState::send_data_frames()`).

**Comment by masaori335** [comment]
I built master and this PR with ThreadSanitizer, and send some traffic by nghttp for regular cases and h2sepc for corner cases.
TSan reported some “lock-order-inversion (potential deadlock)” . But there’re no difference between master branch and this PR.

**Comment by maskit** [comment]
Sounds like we need one more issue for it. Does it survive tons of requests from h2load?

**Comment by shinrich** [comment]
So we should always fetch the session lock then the stream lock?  Or visa versa?

**Comment by zwoop** [comment]
[approve ci debian]

**Comment by masaori335** [comment]
If above TSan reports are not false positive, the lock order should be consistent. Also we need to take care of the order of (Http2ConnectionState - Http2Stream) and (Http2ConnectionState - Http2ClientSession). I think the lock order should be below, because this is the order of those objects are created.

- Http2ClientSession -> Http2ConnectionState -> Http2Stream

BTW, some of above TSan reports might be false positive, because some functions of Http2Stream are sending the cross-thread-event to owning thread. If all events are processed on same thread (not sure this is right thing), the lock-order-inversion doesn't trigger deadlock.

**Comment by masaori335** [comment]
The three TSan reports for this PR looks fails positive. I think we can leave it.

### a) Http2Stream vs Http2ConnectionState
```
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=1662)
#4 Http2Stream::update_read_request(long, bool, bool) /home/masaori/src/github.com/apache/trafficserver/proxy/http2/Http2Stream.cc:478 (traffic_server+0x0000006fad94)
#4 Http2Stream::update_write_request(IOBufferReader*, long, bool) /home/masaori/src/github.com/apache/trafficserver/proxy/http2/Http2Stream.cc:603 (traffic_server+0x0000006fbe08)
```
- Full TSan Report : https://paste.apache.org/wCAQ
- This looks false positive because `Http2Stream::update_read_request()` and `Http2Stream::update_write_request()` always run on same thread

### b) Http2Stream vs Http2ConnectionState
```
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=20208)-
#4 Http2Stream::update_read_request(long, bool, bool) /home/masaori/src/github.com/apache/trafficserver/proxy/http2/Http2Stream.cc:478 (traffic_server+0x0000006fad94)-
#4 Http2Stream::terminate_if_possible() /home/masaori/src/github.com/apache/trafficserver/proxy/http2/Http2Stream.cc:378 (traffic_server+0x0000006f9e40)
```
- Full TSan Report : https://paste.apache.org/Mpln
- This looks false positive because `Http2Stream::main_event_handler()` and `Http2Stream::update_read_request()` always run on same thread

### c) Http2ConnectionState vs Http2ClientSession
```
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=20208)-
#4 send_connection_event /home/masaori/src/github.com/apache/trafficserver/proxy/http2/Http2ClientSession.cc:57 (traffic_server+0x000000708a2d)-
#4 Http2ConnectionState::send_headers_frame(Http2Stream*) /home/masaori/src/github.com/apache/trafficserver/proxy/http2/Http2ConnectionState.cc:1453 (traffic_server+0x0000007188e0)
```
- Full TSan Report : https://paste.apache.org/yW4X
- This looks false positive because `Http2Stream::update_write_request()` sends cross-thread event to same thread of `Http2ClientSession::start()` is processed.

**Comment by bryancall** [comment]
[approve ci debian]

**Comment by masaori335** [comment]
Now, the issue #3100 b) doesn't looks serious in our production. So let's change the release target to 7.2.0 or 8.0.0. At least, this doesn't hold up 7.1.3 release.

**Comment by zwoop** [comment]
This doesn't cherry-pick cleanly, it looks like a trivial change, but lets stick to the protocol and make a 7.1.x PR please.
