### PR TITLE
Mark H2 connection inactive only if it is NOT shutting down

### LINKED ISSUE #4504: Crash on Http2ConnectionState::release_stream()
We got this crash on 8.0.x. This looks pretty similar to #4158. So #4158 (adding null check) could be workaround fix. But it looks like there is a race on shutdown which we should fix.

```
[ 0  ] libc-2.12.so       __libc_waitpid                                               ( :undefined                   ) 
[ 1  ] traffic_server     crash_logger_invoke                                          ( Crash.cc:165                 ) 
[ 2  ] libc-2.12.so       0x2b0b38dfd570                                               ( :undefined                   ) 
[ 3  ] traffic_server     Http2ConnectionState::release_stream(Http2Stream*)           ( Http2ConnectionState.cc:1261 ) 
[ 4  ] traffic_server     Http2Stream::destroy()                                       ( Http2Stream.cc:730           ) 
[ 5  ] traffic_server     Http2Stream::terminate_if_possible()                         ( Http2Stream.cc:380           ) 
[ 6  ] traffic_server     Http2Stream::main_event_handler(int, void*)                  ( Http2Stream.cc:131           ) 
[ 7  ] traffic_server     handleEvent                                                  ( I_Continuation.h:160         ) 
[ 8  ] traffic_server     EThread::process_event(Event*, int)                          ( UnixEThread.cc:131           ) 
[ 9  ] traffic_server     EThread::process_queue(Queue<Event, Event::Link_link>*, i... ( UnixEThread.cc:170           ) 
[ 10 ] traffic_server     EThread::execute_regular()                                   ( UnixEThread.cc:230           ) 
[ 11 ] traffic_server     spawn_thread_internal                                        ( Thread.cc:85                 ) 
[ 12 ] libpthread-2.12.so start_thread                                                 ( :undefined                   )
```

https://github.com/apache/trafficserver/blob/8c50c75ac5faccbc2aa7d1b3880a7c4205ad8c96/proxy/http2/Http2ConnectionState.cc#L1257-L1265

### PR DESCRIPTION
**Pull request by masaori335**
Prior this change, HTTP/2 connection is marked as inactive regardless it is shutting down or not.
I think we don't need to add it to keep-alive queue, if it is shutting down.

Fix #4504

### CODE REVIEW

File: proxy/http2/Http2ConnectionState.cc [hunk 1]
```diff
@@ -1265,6 +1258,15 @@ Http2ConnectionState::release_stream(Http2Stream *stream)
...
       } else if (shutdown_state == HTTP2_SHUTDOWN_IN_PROGRESS && fini_event == nullptr) {
         fini_event = this_ethread()->schedule_imm_local((Continuation *)this, HTTP2_SESSION_EVENT_FINI);
+      } else if (ua_session->is_active()) {
+        // If the number of clients is 0, HTTP2_SESSION_EVENT_FINI is not received or sent, and ua_session is active,
+        // then mark the connection as inactive
+        ua_session->clear_session_active();
+        UnixNetVConnection *vc = static_cast<UnixNetVConnection *>(ua_session->get_netvc());
+        if (vc && vc->active_timeout_in == 0) {
+          // With heavy traffic, ua_session could be destroyed. Do not touch ua_session after this.
+          vc->add_to_keep_alive_queue();
```
Comment (maskit) [inline proxy/http2/Http2ConnectionState.cc]: Looks good, however, will Http2ClientSesion::destroy() be called somewhere in `vc->add_to_keep_alive_queue()` when it frees a session?
I'm not sure if it can be a problem, but if the `destroy()` wasn't called, it means SSN_CLOSE event wouldn't be fired on the session.

Comment (masaori335) [reply proxy/http2/Http2ConnectionState.cc]: When `vc->add_to_keep_alive_queue()` close connection, `VC_EVENT_INACTIVITY_TIMEOUT (105)` comes to `Http2ClientSession::main_event_handler()`. It looks like it calls `Http2ClientSession::destroy()` eventually. 

Below is backtrace from `VC_EVENT_INACTIVITY_TIMEOUT (105)` event on `Http2ClientSession::main_event_handler()` to `Http2ClientSession::destroy()`.

```
(lldb) bt
* thread #2, name = '[ET_NET 4]', stop reason = step in
  * frame #0: 0x00000001001b81d0 traffic_server`Http2ClientSession::destroy(this=0x00000000077ecb00) at Http2ClientSession.cc:66
    frame #1: 0x00000001001c16ac traffic_server`Http2ConnectionState::release_stream(this=0x00000000077ece10, stream=0x0000000000000000) at Http2ConnectionState.cc:1254
    frame #2: 0x00000001001bf7a8 traffic_server`Http2ConnectionState::main_event_handler(this=0x00000000077ece10, event=2252, edata=0x00000000077ecb00) at Http2ConnectionState.cc:910
    frame #3: 0x0000000100017bd1 traffic_server`Continuation::handleEvent(this=0x00000000077ece10, event=2252, data=0x00000000077ecb00) at I_Continuation.h:190
    frame #4: 0x00000001001b997c traffic_server`send_connection_event(cont=0x00000000077ece10, event=2252, edata=0x00000000077ecb00) at Http2ClientSession.cc:58
    frame #5: 0x00000001001ba3f4 traffic_server`Http2ClientSession::do_io_close(this=0x00000000077ecb00, alerrno=-1) at Http2ClientSession.cc:259
    frame #6: 0x00000001001b8f47 traffic_server`Http2ClientSession::main_event_handler(this=0x00000000077ecb00, event=105, edata=0x0000000000fe4d88) at Http2ClientSession.cc:333
```

**Comment by zwoop** [comment]
Please make a PR for 7.1.x please, looks good so far on 8.

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x
