### PR TITLE
Issue #4294: Handle return value of SSL_write() properly

### LINKED ISSUE #4294: Incorrect Error Check in function SSL_write()
Hi,
Function SSL_write() returns the value of 0 and less than 0 are both on error. However , the return value of function SSL_write() is not checked correctly, which forgot to check the return value 0. See the following code:

line : 1098, 1101
https://github.com/apache/trafficserver/blob/5ee6a5f554880b02535e6ee84268df922e87274d/tools/http_load/http_load.c#L1097-L1106

The same situation is  also occured on line 1216, 1219

https://github.com/apache/trafficserver/blob/5ee6a5f554880b02535e6ee84268df922e87274d/tools/http_load/http_load.c#L1215-L1224

===============================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/apps folder

Ref : https://github.com/openssl/openssl/blob/0db957dbbcf6a432086ab913378c23636d8c374c/apps/s_time.c#L231-L232

```c
line 231:     if (buf_len <= 0 || SSL_write(scon, buf, buf_len) <= 0)
line 232:         goto end;
```

Chi Li, Zuxing Gu, Jiecheng Wu

### PR DESCRIPTION
**Pull request by PSUdaemon**
This closes #4294.

### CODE REVIEW

File: tests/gold_tests/tls/ssl-post.c [hunk 1]
```diff
@@ -134,15 +134,15 @@ spawn_same_session_send(void *arg)
     ret = select(sfd + 1, &reads, &writes, NULL, NULL);
     if (FD_ISSET(sfd, &reads) || FD_ISSET(sfd, &writes)) {
       ret = write_ret = SSL_write(ssl, req_buf, strlen(req_buf));
-      if (write_ret >= 0)
+      if (write_ret > 0)
         post_write_ret = SSL_write(ssl, post_buf, sizeof(post_buf));
     }
   }
 
-  while (write_ret < 0) {
```
Comment (bryancall) [inline tests/gold_tests/tls/ssl-post.c]: Seems like this could go into an infinite loop if the connection is closed. https://www.openssl.org/docs/man1.1.1/man3/SSL_write.html

Comment (PSUdaemon) [reply tests/gold_tests/tls/ssl-post.c]: I agree, however, wasn't that the case prior to the change? I'm assuming that since this is a test at some point the CI will timeout and fail the tests. If you'd like to see the proper error handling added here, this will be a more significant change. I would also wonder, would you prefer I remove the changes to this test instead?

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
