### PR TITLE
Fix hosting.config reload

### LINKED ISSUE #7220: hosting.config requires restart, but docs say reloadable
Docs say that hosting.config changes are reloadable:
https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/files/hosting.config.en.html
"After you modify hosting.config, navigate to the Traffic Server bin directory and run traffic_ctl config reload to apply your changes."
This line has been in the docs since the initial release.

In testing, we observe that changes to hosting.config only take effect after restart. The best way I've found to see this:
- make a host with 2 volumes. In hosting.config have
```hostname=* volume=1```
- after starting up, fetch objects. ```traffic_ctl metric match volume | grep bytes_used``` should show ```proxy.process.cache.volume_1.bytes_used``` increasing.
- edit hosting.config, adding the origin (for example ```hostname=origin.example.org volume=2```
- reload trafficserver
- fetch more objects. You'd expect ```proxy.process.cache.volume_2.bytes_used``` to now increase, however, volume_1 continues to increase instead.
- Upon restart and more fetches, ```proxy.process.cache.volume_2.bytes_used``` begins increasing.

Our primary use case for the hosting.config is to assign "properties" that either have low max-age or useful lifetime (for instance a live sports stat object may be constantly updated; a live video segment is only fetched in a small time window). Being able to dynamically add such use cases would be useful.

### PR DESCRIPTION
**Pull request by rob05c**
This is an alternative to https://github.com/apache/trafficserver/pull/8664. That PR is fine in-itself and fixes a bug around the the atomic swap not actually reloading. But fixing that bug so that reloading hosting.config works exposes another deeper bug: the reloaded object has no synchronization around it. 

Not only is the pointer itself never read with synchronization, even if it were, the object itself is never synchronized. So even if the pointer were atomic, the object reads could get different variables from different objects, when callers that need multiple variables really need them to come from a single object. Worse, if a request takes longer than the arbitrary delete timer, it could access freed memory.

This fixes the object to be synchronized, and all access behind a mutex. The reload swap and bad drive removal acquire a write lock, and all other accesses (none of which modify the object) acquire a read lock.

I really don't like adding a mutex to the request path. But the only other options I see are an incredibly complex and bug-prone lock-free solution, or not making it possible to reload hosting.config. As much as I dislike it, the mutex should never have contention except on reload or drive failure. So it's probably actually faster and fewer atomic instructions than even a lock-free solution.

This also adds some helper classes, to make it impossible to accidentally forget to acquire or release the mutex, or modify the object with a readlock, via RAII idioms.

Recommend backporting to 9.2.

Fixes #7220

### CODE REVIEW

**Comment by traeak** [comment]
[approve ci docs]

**Comment by bryancall** [comment]
[approve ci autest]

**Review by SolidWallOfCode — APPROVED** [review]
I wonder about line 284, though - there doesn't seem to be a provision for a failure on a reload.

File: iocore/cache/P_CacheHosting.h [hunk 1]
```diff
@@ -152,23 +261,34 @@ class CacheHostTable
...
+
+    CacheType type = CACHE_HTTP_TYPE;
+    Cache *cache   = nullptr;
+    {
+      ReplaceablePtr<CacheHostTable>::ScopedReader hosttable(ppt);
+      type  = hosttable->type;
+      cache = hosttable->cache;
+    }
+    ppt->reset(new CacheHostTable(cache, type));
+    // new_Deleter(old, CACHE_MEM_FREE_TIMEOUT);
```
Comment (randall) [inline iocore/cache/P_CacheHosting.h:285]: remove commented out code.

Comment (rob05c) [reply iocore/cache/P_CacheHosting.h]: Removed

**Review by randall — APPROVED** [review]

**Comment by rob05c** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x
