### PR TITLE
Check bounds before accessing Vol::evacuate array

### LINKED ISSUE #8647: SIGSEGV on Vol::force_evacuate_head
# Backtrace
```
[ 00 ] libpthread-2.17.so  waitpid                                                              
[ 01 ] traffic_server      crash_logger_invoke(int, siginfo_t*, void*)                          ( Crash.cc:168 )
[ 02 ] libpthread-2.17.so                                                                       
[ 03 ] traffic_server      Vol::force_evacuate_head(Dir*, int)                                  ( P_CacheVol.h:461 )
[ 04 ] traffic_server      CacheVC::openReadClose(int, Event*)                                  ( CacheRead.cc:542 )
[ 05 ] traffic_server      CacheVC::calluser(int)                                               ( P_CacheInternal.h:705 )
[ 06 ] traffic_server      CacheVC::openReadMain(int, Event*)                                   ( CacheRead.cc )
[ 07 ] traffic_server      CacheVC::openReadReadDone(int, Event*)                               ( CacheRead.cc:639 )
[ 08 ] traffic_server      CacheVC::handleReadDone(int, Event*)                                 ( eventsystem/I_Continuation.h:219 )
[ 09 ] traffic_server      CacheVC::openReadMain(int, Event*)                                   ( eventsystem/I_Continuation.h:219 )
[ 10 ] traffic_server      EThread::process_event(Event*, int)                                  ( I_Continuation.h:219 )
[ 11 ] traffic_server      EThread::process_queue(Queue<Event, Event::Link_link>*, int*, int*)  ( UnixEThread.cc:162 )
[ 12 ] traffic_server      EThread::execute_regular()                                           ( UnixEThread.cc:222 )
[ 13 ] traffic_server      EThread::execute()                                                   ( UnixEThread.cc:327 )
[ 14 ] traffic_server      spawn_thread_internal(void*) [clone .llvm.4297563414356737819]       ( Thread.cc:92 )
[ 15 ] libpthread-2.17.so  start_thread                                                         
```

# Affected Versions

We faced this crash with 8.0.x, 8.1.x, and 9.0.x intermittently.

### PR DESCRIPTION
**Pull request by cmcfarlen**
Fixes #8647

This PR does bounds checking on the `Vol::evacuate` array.  While this may fix crashes related to `Dir` entries with invalid offsets, it does not address whatever happened to generate the bad offsets.  So this is a partial fix at best.

There are other places where this array is accessed unchecked from `dir_evac_bucket` but these are the places that are involved in the reported crash.

### CODE REVIEW

**Comment by bryancall** [comment]
I will look at it.

File: iocore/cache/P_CacheVol.h [hunk 1]
```diff
@@ -206,6 +206,12 @@ struct Vol : public Continuation {
   int dir_check(bool fix);
   int db_check(bool fix);
 
+  bool
+  evac_bucket_valid(off_t bucket)
+  {
+    return (bucket >= 0 && bucket < evacuate_size);
```
Comment (SolidWallOfCode) [inline iocore/cache/P_CacheVol.h:212]: How can an `off_t` be less than zero?

**Comment by SolidWallOfCode** [comment]
Looks reasonable to me.

File: iocore/cache/P_CacheVol.h (hunk 1 above)
Comment (cmcfarlen) [reply iocore/cache/P_CacheVol.h:212]: The macro `dir_evac_bucket` produces a `long long` and seem to be stored as `off_t` in other places in the code so I thought it might be a reasonable type for the argument here.  `off_t` is a signed type so I check for >= 0.  Ideally the macro would return an unsigned bucket, but I'm not sure the implication of that change.

**Review by bryancall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x
