### PR TITLE
Fix a crash due to unsatisfied precondition

### LINKED ISSUE #12445: Regression test (-R 3) crashes
Regression test (-R 3) crashes on master and 10.1.x.
```
RPRINT ram_cache: RamCache CLFUS Nominal Size 268435456 Size 266758096
    REGRESSION_RESULT ram_cache:                                PASSED
REGRESSION TEST cache_disk_replacement_stability started
Process 24055 stopped
* thread #12, name = '[ET_NET 9]', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000019621aa44 libsystem_platform.dylib`_platform_strlen + 4
libsystem_platform.dylib`_platform_strlen:
->  0x19621aa44 <+4>:  ldr    q0, [x1]
    0x19621aa48 <+8>:  adr    x3, 0x19621a980 ; ___lldb_unnamed_symbol320
    0x19621aa4c <+12>: ldr    q2, [x3], #0x10
    0x19621aa50 <+16>: and    x2, x0, #0xf
Target 0: (traffic_server) stopped.
(lldb) bt
* thread #12, name = '[ET_NET 9]', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000019621aa44 libsystem_platform.dylib`_platform_strlen + 4
    frame #1: 0x000000010018c250 traffic_server`Stripe::Stripe(CacheDisk*, long long, long long, int, int) [inlined] Stripe::_init_hash_text(this=0x0000000178a28040, disk=0x0000000103a970f8, blocks=119406592, dir_skip=0) at Stripe.cc:104:33 [opt]
    frame #2: 0x000000010018c23c traffic_server`Stripe::Stripe(this=0x0000000178a28040, disk=0x0000000103a970f8, blocks=119406592, dir_skip=0, avg_obj_size=-1, fragment_size=<unavailable>) at Stripe.cc:95:9 [opt]
    frame #3: 0x000000010018dad4 traffic_server`StripeSM::StripeSM(this=0x0000000178a28000, disk=0x0000000103a970f8, blocks=119406592, dir_skip=0, avg_obj_size=-1, fragment_size=-1) at StripeSM.cc:117:5 [opt]
    frame #4: 0x0000000100195528 traffic_server`RegressionTest_cache_disk_replacement_stability(RegressionTest*, int, int*) [inlined] std::__1::__unique_if<StripeSM>::__unique_single std::__1::make_unique[abi:ne190102]<StripeSM, CacheDisk*, long long, int>(__args=<unavailable>, __args=<unavailable>, __args=<unavailable>) at unique_ptr.h:635:30 [opt]
    frame #5: 0x0000000100195504 traffic_server`RegressionTest_cache_disk_replacement_stability(t=0x0000000100522370, level=<unavailable>, pstatus=0x00000001005223a0) at CacheTest.cc:457:22 [opt]
    frame #6: 0x0000000100ac9414 libtscore.dylib`RegressionTest::run(char const*, int) [inlined] start_test(t=0x0000000100522370, regression_level=3) at Regression.cc:83:3 [opt]
    frame #7: 0x0000000100ac93e4 libtscore.dylib`RegressionTest::run(atest=<unavailable>, regression_level=3) at Regression.cc:106:17 [opt]
    frame #8: 0x00000001000118f0 traffic_server`(anonymous namespace)::RegressionCont::mainEvent(this=0x00000001061ed590, event=<unavailable>, e=<unavailable>) at traffic_server.cc:1564:25 [opt]
    frame #9: 0x000000010027628c traffic_server`EThread::process_event(Event*, int) [inlined] Continuation::handleEvent(this=<unavailable>, event=2, data=0x000000010172eba0) at Continuation.h:228:12 [opt]
    frame #10: 0x0000000100276228 traffic_server`EThread::process_event(this=0x00000001028f30c0, e=0x000000010172eba0, calling_code=2) at UnixEThread.cc:166:22 [opt]
    frame #11: 0x0000000100276a00 traffic_server`EThread::execute_regular(this=0x00000001028f30c0) at UnixEThread.cc:273:11 [opt]
    frame #12: 0x00000001002771a4 traffic_server`EThread::execute(this=0x00000001028f30c0) at UnixEThread.cc:358:11 [opt]
    frame #13: 0x00000001002755b4 traffic_server`spawn_thread_internal(a=0x0000000101752880) at Thread.cc:0 [opt]
    frame #14: 0x00000001961e3c0c libsystem_pthread.dylib`_pthread_start + 136
```

```
(lldb) f 1
warning: traffic_server was compiled with optimization - stepping may behave oddly; variables may not be available.
frame #1: 0x000000010018c250 traffic_server`Stripe::Stripe(CacheDisk*, long long, long long, int, int) [inlined] Stripe::_init_hash_text(this=0x0000000178a28040, disk=0x0000000103a970f8, blocks=119406592, dir_skip=0) at Stripe.cc:104:33 [opt]
   101 	Stripe::_init_hash_text(CacheDisk const *disk, off_t blocks, off_t dir_skip)
   102 	{
   103 	  char const  *seed_str       = disk->hash_base_string ? disk->hash_base_string : disk->path;
-> 104 	  const size_t hash_seed_size = strlen(seed_str);
   105 	  const size_t hash_text_size = hash_seed_size + 32;
   106 	
   107 	  this->hash_text = static_cast<char *>(ats_malloc(hash_text_size));
(lldb) p seed_str
(const char *) 0x0000000000000000
(lldb) p disk->hash_base_string
(const ats_scoped_str) {
  ats_scoped_resource<detail::SCOPED_MALLOC_TRAITS<char> > = (_r = 0x0000000000000000)
}
(lldb) p disk->path
(char *const) 0x0000000000000000
```

### PR DESCRIPTION
**Pull request by cmcfarlen**
The Stripe constructor init expects the disk hash_base_string to be a valid value.

I use a placeholder value rather than check for nullptr at the use site because it isn't clear how that code could proceed if nullptr so its probably best to crash there.

fixes #12445

### CODE REVIEW

File: src/api/InkAPITest.cc [hunk 1]
```diff
@@ -917,9 +917,11 @@ synserver_vc_accept(TSCont contp, TSEvent event, void *data)
   TSAssert(s->magic == MAGIC_ALIVE);
 
   if (event == TS_EVENT_NET_ACCEPT_FAILED) {
-    Warning("Synserver failed to bind to port %d.", ntohs(s->accept_port));
-    ink_release_assert(!"Synserver must be able to bind to a port, check system netstat");
-    Dbg(dbg_ctl_SockServer, "%s: NET_ACCEPT_FAILED", __func__);
+    if (s && s->accept_port != SYNSERVER_DUMMY_PORT) {
```
Comment (cmcfarlen) [inline src/api/InkAPITest.cc:920]: Afaict, a close was inserted somewhere that ended up calling this even though in this dummy case, the connection was never established.  Just checking for this case seems to fix the regression test.  Is it correct? Who knows?!

Comment (bneradt) [reply src/api/InkAPITest.cc:920]: I was a little concerned about this happening to match in production, but then noticed SYNSERVER_DUMMY_PORT is -1. :)

**Review by bneradt — APPROVED** [review]

**Review by JosiahWI — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to 10.1.x branch
