### PR TITLE
Fix lookup split dns rule with fast path

### LINKED ISSUE #7319: 9.0.x SplitDNS is not working
On investigation of #7315, I found that SplitDNS is not working at master & 9.0.x with the same configs which I used for 8.1.x.

Debug log says the splitdns fallback to default dns resolver.
```
[Nov 13 16:18:29.545] [ET_NET 11] DEBUG: <SplitDNS.cc:186 (getDNSRecord)> (splitdns) Called SplitDNS::getDNSRecord(example.com)
[Nov 13 16:18:29.545] [ET_NET 11] DEBUG: <SplitDNS.cc:200 (getDNSRecord)> (splitdns) Fail to match a valid splitdns rule, fallback to default dns resolver
```

It looks like `SplitDNS::findServer()` always returns `DNS_SRVR_UNDEFINED` when the fast path is enabled (`SplitDNS::m_bEnableFastPath`).

### PR DESCRIPTION
**Pull request by masaori335**
Fix #7319.

### CODE REVIEW

File: iocore/dns/SplitDNS.cc [hunk 1]
```diff
@@ -222,38 +222,36 @@ SplitDNS::findServer(RequestData *rdata, SplitDNSResult *result)
...
+  if (m_bEnableFastPath && m_pxLeafArray) {
     SplitDNSRecord *data_ptr = nullptr;
     char *pHost              = const_cast<char *>(rdata->get_host());
     if (nullptr == pHost) {
       Warning("SplitDNS: No host to match !");
       return;
     }
 
-    int len        = strlen(pHost);
-    HostLeaf *pxHL = static_cast<HostLeaf *>(m_pxLeafArray);
```
Comment (masaori335) [inline iocore/dns/SplitDNS.cc:234]: I'm not familiar with `iocore/HostLookup.h`, but I'm pretty sure this cast is wrong.

**Review by shinrich — APPROVED** [review]
I am not so familiar with the SplitDNS path, but piece-wise these changes seem reasonable.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
