### PR TITLE
Prevent HttpSM to be added to wrong ConnectingEntry

### LINKED ISSUE #10455: Crash triggered by use-after-free of HttpSM
Encountered this crash in production running our internal 9.x that seems like a use-after-free of HttpSM:
```
#0  Mutex_lock (t=0x7fb2bfffb440, m=0x0)
    at ts/iocore/eventsystem/I_Lock.h
#1  Mutex_lock (m=..., m=..., t=0x7fb2bfffb440)
    at ts/iocore/eventsystem/I_Lock.h
#2  MutexLock::MutexLock (t=0x7fb2bfffb440, am=..., this=0x7fb2b4dfd5e0)
    at ts/iocore/eventsystem/I_Lock.h
#3  ConnectingEntry::state_http_server_open (this=0x7fb186b95200, event=105, 
    data=0x7fb2a58a6280)
    at ts/proxy/http/ConnectingEntry.cc
#4  0x0000000000856a04 in Continuation::handleEvent (data=0x7fb2a58a6280, event=105, 
    this=0x7fb186b95200)
    at ts/iocore/eventsystem/I_Continuation.h
#5  Continuation::handleEvent (data=0x7fb2a58a6280, event=105, this=0x7fb186b95200)
    at ts/iocore/eventsystem/I_Continuation.h
#6  write_signal_and_update (event=105, vc=0x7fb2a58a6000)
    at ts/iocore/net/UnixNetVConnection.cc
#7  0x000000000085b151 in UnixNetVConnection::mainEvent (this=0x7fb2a58a6000, 
    event=<optimized out>, e=<optimized out>)
    at ts/iocore/net/UnixNetVConnection.cc
#8  0x000000000084aadb in InactivityCop::check_inactivity (this=0x7fb2a57ca000, 
    event=<optimized out>, e=0x7fb2a5700060)
    at ts/iocore/net/UnixNet.cc
#9  0x000000000089d79c in Continuation::handleEvent (data=0x7fb2a5700060, event=2, 
    this=<optimized out>)
    at ts/iocore/eventsystem/I_Continuation.h
#10 Continuation::handleEvent (data=0x7fb2a5700060, event=2, this=<optimized out>)
    at ts/iocore/eventsystem/I_Continuation.h
#11 EThread::process_event (this=0x7fb2bfffb440, e=0x7fb2a5700060, calling_code=2)
    at ts/iocore/eventsystem/UnixEThread.cc
#12 0x000000000089e154 in EThread::execute_regular (this=this@entry=0x7fb2bfffb440)
    at ts/iocore/eventsystem/UnixEThread.cc
#13 0x000000000089e676 in EThread::execute (this=0x7fb2bfffb440)
    at ts/iocore/eventsystem/UnixEThread.cc
#14 0x000000000089cc12 in spawn_thread_internal (a=0x7fb2c7e58340)
    at ts/iocore/eventsystem/Thread.cc
#15 0x00007fb2c9cfa1ca in start_thread () from /lib64/libpthread.so.0
#16 0x00007fb2c8e32e73 in clone () from /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by lzx404243**
This PR fixes #10455, a crash observed in production coincided with changes in https://github.com/apache/trafficserver/pull/10157. Please see details in the issue.

### CODE REVIEW

File: proxy/http/ConnectingEntry.cc [hunk 1]
```diff
@@ -152,13 +152,12 @@ ConnectingEntry::state_http_server_open(int event, void *data)
 void
 ConnectingEntry::remove_entry()
 {
-  EThread *ethread = this_ethread();
-  auto ip_iter     = ethread->connecting_pool->m_ip_pool.find(this->ipaddr);
-  while (ip_iter != ethread->connecting_pool->m_ip_pool.end() && this->ipaddr == ip_iter->first) {
+  EThread *ethread            = this_ethread();
+  auto [iter_start, iter_end] = ethread->connecting_pool->m_ip_pool.equal_range(this->ipaddr);
```
Comment (shinrich) [inline proxy/http/ConnectingEntry.cc:156]: So using equal_range is the key to the fix?  equal_range will use the IpHelper compare operator that now includes the port and the IP address.  The original find() will also use the ip address and port, but the ipaddr comparison in the while loop will not.

Assuming I'm understanding that correctly, the changes look good to me.

**Review by shinrich — APPROVED** [review]

File: proxy/http/ConnectingEntry.cc (hunk 1 above)
Comment (bneradt) [reply proxy/http/ConnectingEntry.cc:156]: Yes, you are correct. Using equal_range uses the new IpHelper comparison which makes selection consistent across the various uses of ip pool.
