### PR TITLE
Fix vc close migration race condition

### LINKED ISSUE #7333: 9.0.x use-after-free crash
We resynced with the ASF 9.0.x branch as of 11/10.  The resulting build crashes for us with production traffic within 15-60 minutes.

I split the discussion of PR #7237 to Issue #7338

The crash with PR #7237 has the InactivityCop on the stack. It appears to be trying to send the inactivity timeout to a freed continuation that is still being referenced by the read.vio.  I believe that I have a fix for this issue, and will post a PR shortly.

The crash associated with PR #7278 appears to be a more general use after free.  We are setting up our prod sim environment with an ASAN build to try and catch a more useful error.

### PR DESCRIPTION
**Pull request by shinrich**
The issue contains the details.  This problem came in with PR #7278.  Once we added that commit, our canary production box would crash at least once an hour with corrupted memory stacks (examples in issue).  We ran an ASAN version of the build in our prod sim and came up with a use-after-free and a very similar double free failure (again stacks in the issue).

The use after free issue was do to the close flag being set early in UnixNetVConnection::do_io_close, but having accesses to the object later.  The other thread would see the close flag set when walking the event look and delete the netvc object from underneath the first thread.

We have been running a build with this patch on a production box for over 3 hours now.  We will expand our testing of this, but it seems likely that this is addressing the crash we were seeing.

This closes #7333

### CODE REVIEW

File: iocore/net/UnixNetVConnection.cc [hunk 1]
```diff
@@ -686,6 +680,14 @@ UnixNetVConnection::do_io_close(int alerrno /* = -1 */)
     this->lerrno = alerrno;
   }
 
+  // Must mark for closed last in case this is a
+  // cross thread migration scenario.
+  if (alerrno == -1) {
```
Comment (sudheerv) [inline iocore/net/UnixNetVConnection.cc:685]: Does setting `closed` here really prevent the use-after-free? Presumably, this thread is still trying to clean up the VC, which means it's still running the ::free/::clear routines. Wouldn't the race still exist for the read ready loop then? I wonder you will still see the issue from ASAN even with this new change.

I think we do need to delay setting the read.vio.cont and write.vio.cont to nullptr in do_io_close to after setting close  flag, as otherwise, the net_read_io may get unblocked on the read vio mutex and run a previously rescheduled read event

**Review by sudheerv — COMMENTED** [review]
Does setting closed here really prevent the use-after-free? Presumably, this thread is still trying to clean up the VC, which means it's still running the ::free/::clear routines. Wouldn't the race still exist for the read ready loop then? I wonder you will still see the issue from ASAN even with this new change.

I think we do need to delay setting the read.vio.cont and write.vio.cont to nullptr in do_io_close to after setting close flag, as otherwise, the net_read_io may get unblocked on the read vio mutex and run a previously rescheduled read event

File: iocore/net/UnixNetVConnection.cc (hunk 1 above)
Comment (shinrich) [reply iocore/net/UnixNetVConnection.cc:685]: I can try moving clearing the vio contintations to the free.  But even reducing the race window this tiny amount seems to have eliminated the crash for us.

**Comment by shinrich** [comment]
Added a commit to defer clearing the the vio continations as @sudheerv suggested.

**Review by sudheerv — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
